#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 220
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 1
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  sym__space = 1,
  sym_comment = 2,
  sym_escape_sequence = 3,
  anon_sym_DQUOTE = 4,
  aux_sym__quoted_literal_token1 = 5,
  sym__unquoted_value = 6,
  aux_sym_key_token1 = 7,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 8,
  sym_multiline_hint = 9,
  aux_sym__multiline_fragment_token1 = 10,
  anon_sym_EQ = 11,
  sym__newline = 12,
  sym__endfile = 13,
  sym__indent = 14,
  sym__outdent = 15,
  sym_line_comment = 16,
  sym_source_file = 17,
  sym__section = 18,
  sym_map = 19,
  sym_list = 20,
  sym__quoted_literal = 21,
  sym_key = 22,
  sym_value = 23,
  aux_sym__line_comments = 24,
  sym_multiline_value = 25,
  sym__multiline_fragment = 26,
  sym__item = 27,
  sym_pair = 28,
  aux_sym_map_repeat1 = 29,
  aux_sym_list_repeat1 = 30,
  aux_sym__quoted_literal_repeat1 = 31,
  aux_sym__multiline_fragment_repeat1 = 32,
  alias_sym_multiline_content = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__space] = "_space",
  [sym_comment] = "comment",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__quoted_literal_token1] = "_quoted_literal_token1",
  [sym__unquoted_value] = "_unquoted_value",
  [aux_sym_key_token1] = "key_token1",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [sym_multiline_hint] = "multiline_hint",
  [aux_sym__multiline_fragment_token1] = "_multiline_fragment_token1",
  [anon_sym_EQ] = "=",
  [sym__newline] = "_newline",
  [sym__endfile] = "_endfile",
  [sym__indent] = "_indent",
  [sym__outdent] = "_outdent",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym__section] = "_section",
  [sym_map] = "map",
  [sym_list] = "list",
  [sym__quoted_literal] = "_quoted_literal",
  [sym_key] = "key",
  [sym_value] = "value",
  [aux_sym__line_comments] = "_line_comments",
  [sym_multiline_value] = "multiline_value",
  [sym__multiline_fragment] = "_multiline_fragment",
  [sym__item] = "_item",
  [sym_pair] = "pair",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym__quoted_literal_repeat1] = "_quoted_literal_repeat1",
  [aux_sym__multiline_fragment_repeat1] = "_multiline_fragment_repeat1",
  [alias_sym_multiline_content] = "multiline_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__space] = sym__space,
  [sym_comment] = sym_comment,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__quoted_literal_token1] = aux_sym__quoted_literal_token1,
  [sym__unquoted_value] = sym__unquoted_value,
  [aux_sym_key_token1] = aux_sym_key_token1,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [sym_multiline_hint] = sym_multiline_hint,
  [aux_sym__multiline_fragment_token1] = aux_sym__multiline_fragment_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__newline] = sym__newline,
  [sym__endfile] = sym__endfile,
  [sym__indent] = sym__indent,
  [sym__outdent] = sym__outdent,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym__section] = sym__section,
  [sym_map] = sym_map,
  [sym_list] = sym_list,
  [sym__quoted_literal] = sym__quoted_literal,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [aux_sym__line_comments] = aux_sym__line_comments,
  [sym_multiline_value] = sym_multiline_value,
  [sym__multiline_fragment] = sym__multiline_fragment,
  [sym__item] = sym__item,
  [sym_pair] = sym_pair,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym__quoted_literal_repeat1] = aux_sym__quoted_literal_repeat1,
  [aux_sym__multiline_fragment_repeat1] = aux_sym__multiline_fragment_repeat1,
  [alias_sym_multiline_content] = alias_sym_multiline_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__unquoted_value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_key_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_multiline_hint] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__multiline_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__endfile] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__outdent] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__section] = {
    .visible = false,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__line_comments] = {
    .visible = false,
    .named = false,
  },
  [sym_multiline_value] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_fragment] = {
    .visible = false,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__quoted_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_multiline_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_multiline_content,
  },
  [2] = {
    [3] = alias_sym_multiline_content,
  },
  [3] = {
    [4] = alias_sym_multiline_content,
  },
  [4] = {
    [5] = alias_sym_multiline_content,
  },
  [5] = {
    [6] = alias_sym_multiline_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__multiline_fragment, 2,
    sym__multiline_fragment,
    alias_sym_multiline_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 17,
  [20] = 11,
  [21] = 13,
  [22] = 14,
  [23] = 18,
  [24] = 16,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 32,
  [33] = 30,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 37,
  [39] = 36,
  [40] = 32,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 46,
  [47] = 30,
  [48] = 48,
  [49] = 49,
  [50] = 41,
  [51] = 51,
  [52] = 43,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 49,
  [57] = 48,
  [58] = 53,
  [59] = 54,
  [60] = 60,
  [61] = 61,
  [62] = 29,
  [63] = 44,
  [64] = 60,
  [65] = 61,
  [66] = 66,
  [67] = 66,
  [68] = 46,
  [69] = 29,
  [70] = 30,
  [71] = 55,
  [72] = 32,
  [73] = 51,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 32,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 79,
  [85] = 85,
  [86] = 86,
  [87] = 85,
  [88] = 88,
  [89] = 89,
  [90] = 83,
  [91] = 82,
  [92] = 92,
  [93] = 92,
  [94] = 94,
  [95] = 74,
  [96] = 80,
  [97] = 88,
  [98] = 94,
  [99] = 76,
  [100] = 100,
  [101] = 78,
  [102] = 75,
  [103] = 80,
  [104] = 76,
  [105] = 80,
  [106] = 76,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 107,
  [114] = 112,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 120,
  [124] = 118,
  [125] = 109,
  [126] = 110,
  [127] = 111,
  [128] = 122,
  [129] = 116,
  [130] = 121,
  [131] = 115,
  [132] = 132,
  [133] = 117,
  [134] = 132,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 138,
  [145] = 145,
  [146] = 135,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 148,
  [151] = 151,
  [152] = 137,
  [153] = 153,
  [154] = 139,
  [155] = 155,
  [156] = 156,
  [157] = 136,
  [158] = 158,
  [159] = 159,
  [160] = 141,
  [161] = 161,
  [162] = 159,
  [163] = 155,
  [164] = 153,
  [165] = 161,
  [166] = 145,
  [167] = 143,
  [168] = 168,
  [169] = 140,
  [170] = 170,
  [171] = 147,
  [172] = 158,
  [173] = 149,
  [174] = 151,
  [175] = 156,
  [176] = 142,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 179,
  [184] = 184,
  [185] = 185,
  [186] = 186,
  [187] = 187,
  [188] = 188,
  [189] = 189,
  [190] = 190,
  [191] = 191,
  [192] = 178,
  [193] = 182,
  [194] = 184,
  [195] = 195,
  [196] = 185,
  [197] = 197,
  [198] = 181,
  [199] = 199,
  [200] = 186,
  [201] = 201,
  [202] = 180,
  [203] = 187,
  [204] = 204,
  [205] = 188,
  [206] = 206,
  [207] = 189,
  [208] = 208,
  [209] = 190,
  [210] = 210,
  [211] = 211,
  [212] = 199,
  [213] = 213,
  [214] = 214,
  [215] = 177,
  [216] = 216,
  [217] = 201,
  [218] = 191,
  [219] = 208,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ';') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ';') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ';') ADVANCE(30);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__quoted_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__unquoted_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ';') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_key_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_multiline_hint);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ';') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__multiline_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 3, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 2},
  [3] = {.lex_state = 1, .external_lex_state = 3},
  [4] = {.lex_state = 1, .external_lex_state = 4},
  [5] = {.lex_state = 1, .external_lex_state = 3},
  [6] = {.lex_state = 1, .external_lex_state = 4},
  [7] = {.lex_state = 3, .external_lex_state = 5},
  [8] = {.lex_state = 3, .external_lex_state = 5},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 4},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 4},
  [29] = {.lex_state = 0, .external_lex_state = 4},
  [30] = {.lex_state = 0, .external_lex_state = 4},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 3, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 3},
  [36] = {.lex_state = 0, .external_lex_state = 6},
  [37] = {.lex_state = 0, .external_lex_state = 6},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 4},
  [41] = {.lex_state = 0, .external_lex_state = 6},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 0, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 4},
  [45] = {.lex_state = 0, .external_lex_state = 4},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 3},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 3},
  [53] = {.lex_state = 0, .external_lex_state = 4},
  [54] = {.lex_state = 0, .external_lex_state = 4},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 3},
  [58] = {.lex_state = 0, .external_lex_state = 3},
  [59] = {.lex_state = 0, .external_lex_state = 3},
  [60] = {.lex_state = 0, .external_lex_state = 3},
  [61] = {.lex_state = 0, .external_lex_state = 6},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 3},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 3},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 6},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 6},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0, .external_lex_state = 3},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 6},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0, .external_lex_state = 6},
  [78] = {.lex_state = 5, .external_lex_state = 7},
  [79] = {.lex_state = 5, .external_lex_state = 7},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 0, .external_lex_state = 8},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 5, .external_lex_state = 7},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 6},
  [88] = {.lex_state = 0, .external_lex_state = 6},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 6},
  [91] = {.lex_state = 0, .external_lex_state = 6},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 6},
  [94] = {.lex_state = 0, .external_lex_state = 6},
  [95] = {.lex_state = 0, .external_lex_state = 6},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 0, .external_lex_state = 8},
  [101] = {.lex_state = 5, .external_lex_state = 7},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 4},
  [106] = {.lex_state = 4},
  [107] = {.lex_state = 0, .external_lex_state = 9},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 9},
  [113] = {.lex_state = 0, .external_lex_state = 10},
  [114] = {.lex_state = 0, .external_lex_state = 10},
  [115] = {.lex_state = 0, .external_lex_state = 10},
  [116] = {.lex_state = 0, .external_lex_state = 10},
  [117] = {.lex_state = 0, .external_lex_state = 7},
  [118] = {.lex_state = 0, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 8},
  [120] = {.lex_state = 0, .external_lex_state = 6},
  [121] = {.lex_state = 0, .external_lex_state = 9},
  [122] = {.lex_state = 0, .external_lex_state = 9},
  [123] = {.lex_state = 0, .external_lex_state = 2},
  [124] = {.lex_state = 0, .external_lex_state = 6},
  [125] = {.lex_state = 0, .external_lex_state = 6},
  [126] = {.lex_state = 0, .external_lex_state = 6},
  [127] = {.lex_state = 0, .external_lex_state = 6},
  [128] = {.lex_state = 0, .external_lex_state = 10},
  [129] = {.lex_state = 0, .external_lex_state = 9},
  [130] = {.lex_state = 0, .external_lex_state = 10},
  [131] = {.lex_state = 0, .external_lex_state = 9},
  [132] = {.lex_state = 0, .external_lex_state = 7},
  [133] = {.lex_state = 0, .external_lex_state = 7},
  [134] = {.lex_state = 0, .external_lex_state = 7},
  [135] = {.lex_state = 0, .external_lex_state = 9},
  [136] = {.lex_state = 19},
  [137] = {.lex_state = 0, .external_lex_state = 10},
  [138] = {.lex_state = 19},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0, .external_lex_state = 9},
  [141] = {.lex_state = 0, .external_lex_state = 7},
  [142] = {.lex_state = 0, .external_lex_state = 7},
  [143] = {.lex_state = 0, .external_lex_state = 9},
  [144] = {.lex_state = 19},
  [145] = {.lex_state = 0, .external_lex_state = 9},
  [146] = {.lex_state = 0, .external_lex_state = 10},
  [147] = {.lex_state = 0, .external_lex_state = 10},
  [148] = {.lex_state = 19},
  [149] = {.lex_state = 0, .external_lex_state = 10},
  [150] = {.lex_state = 19},
  [151] = {.lex_state = 0, .external_lex_state = 10},
  [152] = {.lex_state = 0, .external_lex_state = 9},
  [153] = {.lex_state = 19},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0, .external_lex_state = 9},
  [156] = {.lex_state = 0, .external_lex_state = 10},
  [157] = {.lex_state = 19},
  [158] = {.lex_state = 0, .external_lex_state = 10},
  [159] = {.lex_state = 0, .external_lex_state = 9},
  [160] = {.lex_state = 0, .external_lex_state = 7},
  [161] = {.lex_state = 19},
  [162] = {.lex_state = 0, .external_lex_state = 10},
  [163] = {.lex_state = 0, .external_lex_state = 10},
  [164] = {.lex_state = 19},
  [165] = {.lex_state = 19},
  [166] = {.lex_state = 0, .external_lex_state = 10},
  [167] = {.lex_state = 0, .external_lex_state = 10},
  [168] = {.lex_state = 19},
  [169] = {.lex_state = 0, .external_lex_state = 10},
  [170] = {.lex_state = 19},
  [171] = {.lex_state = 0, .external_lex_state = 9},
  [172] = {.lex_state = 0, .external_lex_state = 9},
  [173] = {.lex_state = 0, .external_lex_state = 9},
  [174] = {.lex_state = 0, .external_lex_state = 9},
  [175] = {.lex_state = 0, .external_lex_state = 9},
  [176] = {.lex_state = 0, .external_lex_state = 7},
  [177] = {.lex_state = 0, .external_lex_state = 7},
  [178] = {.lex_state = 0, .external_lex_state = 11},
  [179] = {.lex_state = 0, .external_lex_state = 11},
  [180] = {.lex_state = 0, .external_lex_state = 11},
  [181] = {.lex_state = 0, .external_lex_state = 11},
  [182] = {.lex_state = 0, .external_lex_state = 11},
  [183] = {.lex_state = 0, .external_lex_state = 11},
  [184] = {.lex_state = 0, .external_lex_state = 11},
  [185] = {.lex_state = 0, .external_lex_state = 11},
  [186] = {.lex_state = 0, .external_lex_state = 11},
  [187] = {.lex_state = 0, .external_lex_state = 11},
  [188] = {.lex_state = 0, .external_lex_state = 11},
  [189] = {.lex_state = 0, .external_lex_state = 11},
  [190] = {.lex_state = 0, .external_lex_state = 11},
  [191] = {.lex_state = 0, .external_lex_state = 11},
  [192] = {.lex_state = 0, .external_lex_state = 11},
  [193] = {.lex_state = 0, .external_lex_state = 11},
  [194] = {.lex_state = 0, .external_lex_state = 11},
  [195] = {.lex_state = 0},
  [196] = {.lex_state = 0, .external_lex_state = 11},
  [197] = {.lex_state = 0, .external_lex_state = 5},
  [198] = {.lex_state = 0, .external_lex_state = 11},
  [199] = {.lex_state = 0, .external_lex_state = 7},
  [200] = {.lex_state = 0, .external_lex_state = 11},
  [201] = {.lex_state = 0, .external_lex_state = 7},
  [202] = {.lex_state = 0, .external_lex_state = 11},
  [203] = {.lex_state = 0, .external_lex_state = 11},
  [204] = {.lex_state = 0},
  [205] = {.lex_state = 0, .external_lex_state = 11},
  [206] = {.lex_state = 0, .external_lex_state = 11},
  [207] = {.lex_state = 0, .external_lex_state = 11},
  [208] = {.lex_state = 0, .external_lex_state = 7},
  [209] = {.lex_state = 0, .external_lex_state = 11},
  [210] = {.lex_state = 0, .external_lex_state = 5},
  [211] = {.lex_state = 0},
  [212] = {.lex_state = 0, .external_lex_state = 7},
  [213] = {.lex_state = 0, .external_lex_state = 5},
  [214] = {.lex_state = 0},
  [215] = {.lex_state = 0, .external_lex_state = 7},
  [216] = {.lex_state = 0},
  [217] = {.lex_state = 0, .external_lex_state = 7},
  [218] = {.lex_state = 0, .external_lex_state = 11},
  [219] = {.lex_state = 0, .external_lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__endfile] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__outdent] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(216),
    [sym__section] = STATE(213),
    [sym_map] = STATE(213),
    [sym_list] = STATE(213),
    [sym__quoted_literal] = STATE(34),
    [sym_key] = STATE(25),
    [aux_sym__line_comments] = STATE(2),
    [sym__item] = STATE(131),
    [sym_pair] = STATE(129),
    [anon_sym_DQUOTE] = ACTIONS(3),
    [aux_sym_key_token1] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
    [sym__endfile] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      aux_sym_key_token1,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(15), 1,
      sym__newline,
    ACTIONS(17), 1,
      sym__endfile,
    ACTIONS(19), 1,
      sym_line_comment,
    STATE(25), 1,
      sym_key,
    STATE(32), 1,
      aux_sym__line_comments,
    STATE(34), 1,
      sym__quoted_literal,
    STATE(129), 1,
      sym_pair,
    STATE(131), 1,
      sym__item,
    STATE(210), 3,
      sym__section,
      sym_map,
      sym_list,
  [39] = 12,
    ACTIONS(21), 1,
      sym__space,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym__unquoted_value,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym__indent,
    ACTIONS(35), 1,
      sym_line_comment,
    STATE(37), 1,
      sym_value,
    STATE(52), 1,
      aux_sym__line_comments,
    STATE(68), 1,
      sym__quoted_literal,
    STATE(87), 1,
      sym_multiline_value,
    ACTIONS(31), 2,
      sym__newline,
      sym__outdent,
  [77] = 12,
    ACTIONS(37), 1,
      sym__space,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym__unquoted_value,
    ACTIONS(45), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(47), 1,
      sym__indent,
    ACTIONS(49), 1,
      sym_line_comment,
    STATE(38), 1,
      sym_value,
    STATE(43), 1,
      aux_sym__line_comments,
    STATE(46), 1,
      sym__quoted_literal,
    STATE(85), 1,
      sym_multiline_value,
    ACTIONS(31), 2,
      sym__newline,
      sym__endfile,
  [115] = 11,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      sym__unquoted_value,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(51), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym__indent,
    ACTIONS(57), 1,
      sym_line_comment,
    STATE(36), 1,
      sym_value,
    STATE(42), 1,
      aux_sym__line_comments,
    STATE(68), 1,
      sym__quoted_literal,
    STATE(94), 1,
      sym_multiline_value,
    ACTIONS(53), 2,
      sym__newline,
      sym__outdent,
  [150] = 11,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym__unquoted_value,
    ACTIONS(45), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(59), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__indent,
    ACTIONS(63), 1,
      sym_line_comment,
    STATE(39), 1,
      sym_value,
    STATE(45), 1,
      aux_sym__line_comments,
    STATE(46), 1,
      sym__quoted_literal,
    STATE(98), 1,
      sym_multiline_value,
    ACTIONS(53), 2,
      sym__newline,
      sym__endfile,
  [185] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      aux_sym_key_token1,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(17), 1,
      sym__endfile,
    STATE(25), 1,
      sym_key,
    STATE(34), 1,
      sym__quoted_literal,
    STATE(129), 1,
      sym_pair,
    STATE(131), 1,
      sym__item,
    STATE(210), 3,
      sym__section,
      sym_map,
      sym_list,
  [215] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      aux_sym_key_token1,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(65), 1,
      sym__endfile,
    STATE(25), 1,
      sym_key,
    STATE(34), 1,
      sym__quoted_literal,
    STATE(129), 1,
      sym_pair,
    STATE(131), 1,
      sym__item,
    STATE(197), 3,
      sym__section,
      sym_map,
      sym_list,
  [245] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(190), 3,
      sym__section,
      sym_map,
      sym_list,
  [272] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(209), 3,
      sym__section,
      sym_map,
      sym_list,
  [299] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(194), 3,
      sym__section,
      sym_map,
      sym_list,
  [326] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(180), 3,
      sym__section,
      sym_map,
      sym_list,
  [353] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(188), 3,
      sym__section,
      sym_map,
      sym_list,
  [380] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(181), 3,
      sym__section,
      sym_map,
      sym_list,
  [407] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(202), 3,
      sym__section,
      sym_map,
      sym_list,
  [434] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(203), 3,
      sym__section,
      sym_map,
      sym_list,
  [461] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(182), 3,
      sym__section,
      sym_map,
      sym_list,
  [488] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(196), 3,
      sym__section,
      sym_map,
      sym_list,
  [515] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(193), 3,
      sym__section,
      sym_map,
      sym_list,
  [542] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(184), 3,
      sym__section,
      sym_map,
      sym_list,
  [569] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(205), 3,
      sym__section,
      sym_map,
      sym_list,
  [596] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(198), 3,
      sym__section,
      sym_map,
      sym_list,
  [623] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(185), 3,
      sym__section,
      sym_map,
      sym_list,
  [650] = 8,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(115), 1,
      sym__item,
    STATE(116), 1,
      sym_pair,
    STATE(187), 3,
      sym__section,
      sym_map,
      sym_list,
  [677] = 8,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(73), 1,
      sym__space,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__indent,
    ACTIONS(81), 1,
      sym_line_comment,
    STATE(73), 1,
      aux_sym__line_comments,
    STATE(152), 1,
      sym__item,
    ACTIONS(77), 2,
      sym__newline,
      sym__endfile,
  [703] = 8,
    ACTIONS(71), 1,
      anon_sym_EQ,
    ACTIONS(83), 1,
      sym__space,
    ACTIONS(85), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym__indent,
    ACTIONS(89), 1,
      sym_line_comment,
    STATE(51), 1,
      aux_sym__line_comments,
    STATE(137), 1,
      sym__item,
    ACTIONS(77), 2,
      sym__newline,
      sym__outdent,
  [729] = 7,
    ACTIONS(71), 1,
      anon_sym_EQ,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym__indent,
    ACTIONS(97), 1,
      sym_line_comment,
    STATE(59), 1,
      aux_sym__line_comments,
    STATE(146), 1,
      sym__item,
    ACTIONS(93), 2,
      sym__newline,
      sym__outdent,
  [752] = 7,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(99), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__indent,
    ACTIONS(103), 1,
      sym_line_comment,
    STATE(54), 1,
      aux_sym__line_comments,
    STATE(135), 1,
      sym__item,
    ACTIONS(93), 2,
      sym__newline,
      sym__endfile,
  [775] = 1,
    ACTIONS(105), 7,
      sym__newline,
      sym__endfile,
      sym__indent,
      sym_line_comment,
      sym__space,
      sym_comment,
      anon_sym_EQ,
  [785] = 1,
    ACTIONS(107), 7,
      sym__newline,
      sym__endfile,
      sym__indent,
      sym_line_comment,
      sym__space,
      sym_comment,
      anon_sym_EQ,
  [795] = 1,
    ACTIONS(105), 7,
      sym__newline,
      sym__indent,
      sym__outdent,
      sym_line_comment,
      sym__space,
      sym_comment,
      anon_sym_EQ,
  [805] = 3,
    ACTIONS(111), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym__line_comments,
    ACTIONS(109), 5,
      sym__newline,
      sym__endfile,
      anon_sym_DQUOTE,
      aux_sym_key_token1,
      anon_sym_EQ,
  [819] = 1,
    ACTIONS(107), 7,
      sym__newline,
      sym__indent,
      sym__outdent,
      sym_line_comment,
      sym__space,
      sym_comment,
      anon_sym_EQ,
  [829] = 1,
    ACTIONS(114), 7,
      sym__newline,
      sym__endfile,
      sym__indent,
      sym_line_comment,
      sym__space,
      sym_comment,
      anon_sym_EQ,
  [839] = 1,
    ACTIONS(114), 7,
      sym__newline,
      sym__indent,
      sym__outdent,
      sym_line_comment,
      sym__space,
      sym_comment,
      anon_sym_EQ,
  [849] = 5,
    ACTIONS(116), 1,
      sym__space,
    ACTIONS(118), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_line_comment,
    STATE(93), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__outdent,
  [866] = 5,
    ACTIONS(124), 1,
      sym__space,
    ACTIONS(126), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_line_comment,
    STATE(75), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__outdent,
  [883] = 5,
    ACTIONS(130), 1,
      sym__space,
    ACTIONS(132), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_line_comment,
    STATE(102), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__endfile,
  [900] = 5,
    ACTIONS(136), 1,
      sym__space,
    ACTIONS(138), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_line_comment,
    STATE(92), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__endfile,
  [917] = 3,
    ACTIONS(142), 1,
      sym_line_comment,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(109), 3,
      sym__newline,
      sym__endfile,
      sym__indent,
  [929] = 4,
    ACTIONS(118), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_line_comment,
    STATE(93), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__outdent,
  [943] = 4,
    ACTIONS(145), 1,
      sym__indent,
    ACTIONS(147), 1,
      sym_line_comment,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__outdent,
  [957] = 4,
    ACTIONS(61), 1,
      sym__indent,
    ACTIONS(149), 1,
      sym_line_comment,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__endfile,
  [971] = 4,
    ACTIONS(151), 1,
      sym__indent,
    ACTIONS(153), 1,
      sym_line_comment,
    STATE(64), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__endfile,
  [985] = 4,
    ACTIONS(149), 1,
      sym_line_comment,
    ACTIONS(151), 1,
      sym__indent,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__endfile,
  [999] = 1,
    ACTIONS(155), 5,
      sym__newline,
      sym__endfile,
      sym_line_comment,
      sym__space,
      sym_comment,
  [1007] = 1,
    ACTIONS(107), 5,
      sym__newline,
      sym__endfile,
      sym_line_comment,
      sym__space,
      sym_comment,
  [1015] = 4,
    ACTIONS(61), 1,
      sym__indent,
    ACTIONS(63), 1,
      sym_line_comment,
    STATE(45), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__endfile,
  [1029] = 4,
    ACTIONS(95), 1,
      sym__indent,
    ACTIONS(97), 1,
      sym_line_comment,
    STATE(59), 1,
      aux_sym__line_comments,
    ACTIONS(93), 2,
      sym__newline,
      sym__outdent,
  [1043] = 4,
    ACTIONS(138), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_line_comment,
    STATE(92), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__endfile,
  [1057] = 4,
    ACTIONS(95), 1,
      sym__indent,
    ACTIONS(147), 1,
      sym_line_comment,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(93), 2,
      sym__newline,
      sym__outdent,
  [1071] = 4,
    ACTIONS(55), 1,
      sym__indent,
    ACTIONS(147), 1,
      sym_line_comment,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__outdent,
  [1085] = 4,
    ACTIONS(159), 1,
      sym__indent,
    ACTIONS(161), 1,
      sym_line_comment,
    STATE(67), 1,
      aux_sym__line_comments,
    ACTIONS(157), 2,
      sym__newline,
      sym__endfile,
  [1099] = 4,
    ACTIONS(149), 1,
      sym_line_comment,
    ACTIONS(159), 1,
      sym__indent,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(157), 2,
      sym__newline,
      sym__endfile,
  [1113] = 5,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_key_token1,
    STATE(26), 1,
      sym_key,
    STATE(35), 1,
      sym__quoted_literal,
    STATE(149), 1,
      sym_pair,
  [1129] = 4,
    ACTIONS(101), 1,
      sym__indent,
    ACTIONS(103), 1,
      sym_line_comment,
    STATE(54), 1,
      aux_sym__line_comments,
    ACTIONS(93), 2,
      sym__newline,
      sym__endfile,
  [1143] = 4,
    ACTIONS(55), 1,
      sym__indent,
    ACTIONS(57), 1,
      sym_line_comment,
    STATE(42), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__outdent,
  [1157] = 4,
    ACTIONS(163), 1,
      sym__indent,
    ACTIONS(165), 1,
      sym_line_comment,
    STATE(66), 1,
      aux_sym__line_comments,
    ACTIONS(157), 2,
      sym__newline,
      sym__outdent,
  [1171] = 4,
    ACTIONS(147), 1,
      sym_line_comment,
    ACTIONS(163), 1,
      sym__indent,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(157), 2,
      sym__newline,
      sym__outdent,
  [1185] = 4,
    ACTIONS(147), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      sym__indent,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__outdent,
  [1199] = 4,
    ACTIONS(171), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_line_comment,
    STATE(90), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__outdent,
  [1213] = 1,
    ACTIONS(105), 5,
      sym__newline,
      sym__endfile,
      sym_line_comment,
      sym__space,
      sym_comment,
  [1221] = 4,
    ACTIONS(145), 1,
      sym__indent,
    ACTIONS(175), 1,
      sym_line_comment,
    STATE(60), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__outdent,
  [1235] = 4,
    ACTIONS(149), 1,
      sym_line_comment,
    ACTIONS(177), 1,
      sym__indent,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__endfile,
  [1249] = 4,
    ACTIONS(179), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_line_comment,
    STATE(83), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__endfile,
  [1263] = 4,
    ACTIONS(147), 1,
      sym_line_comment,
    ACTIONS(185), 1,
      sym__indent,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(183), 2,
      sym__newline,
      sym__outdent,
  [1277] = 4,
    ACTIONS(149), 1,
      sym_line_comment,
    ACTIONS(187), 1,
      sym__indent,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(183), 2,
      sym__newline,
      sym__endfile,
  [1291] = 1,
    ACTIONS(155), 5,
      sym__newline,
      sym__outdent,
      sym_line_comment,
      sym__space,
      sym_comment,
  [1299] = 1,
    ACTIONS(105), 5,
      sym__newline,
      sym__outdent,
      sym_line_comment,
      sym__space,
      sym_comment,
  [1307] = 1,
    ACTIONS(107), 5,
      sym__newline,
      sym__outdent,
      sym_line_comment,
      sym__space,
      sym_comment,
  [1315] = 5,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      aux_sym_key_token1,
    STATE(25), 1,
      sym_key,
    STATE(34), 1,
      sym__quoted_literal,
    STATE(173), 1,
      sym_pair,
  [1331] = 3,
    ACTIONS(189), 1,
      sym_line_comment,
    STATE(72), 1,
      aux_sym__line_comments,
    ACTIONS(109), 3,
      sym__newline,
      sym__indent,
      sym__outdent,
  [1343] = 4,
    ACTIONS(101), 1,
      sym__indent,
    ACTIONS(149), 1,
      sym_line_comment,
    STATE(40), 1,
      aux_sym__line_comments,
    ACTIONS(93), 2,
      sym__newline,
      sym__endfile,
  [1357] = 3,
    ACTIONS(181), 1,
      sym_line_comment,
    STATE(83), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__endfile,
  [1368] = 3,
    ACTIONS(192), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__outdent,
  [1379] = 3,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(80), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(194), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1390] = 3,
    ACTIONS(198), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym__line_comments,
    ACTIONS(109), 2,
      sym__newline,
      sym__outdent,
  [1401] = 4,
    ACTIONS(201), 1,
      sym__space,
    ACTIONS(203), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_multiline_hint,
    ACTIONS(207), 1,
      sym__indent,
  [1414] = 4,
    ACTIONS(209), 1,
      sym__space,
    ACTIONS(211), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_multiline_hint,
    ACTIONS(215), 1,
      sym__indent,
  [1427] = 3,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(217), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1438] = 4,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(223), 1,
      sym__indent,
    ACTIONS(225), 1,
      sym__outdent,
    STATE(86), 1,
      aux_sym__multiline_fragment_repeat1,
  [1451] = 3,
    ACTIONS(229), 1,
      sym_line_comment,
    STATE(97), 1,
      aux_sym__line_comments,
    ACTIONS(227), 2,
      sym__newline,
      sym__endfile,
  [1462] = 3,
    ACTIONS(19), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym__line_comments,
    ACTIONS(227), 2,
      sym__newline,
      sym__endfile,
  [1473] = 4,
    ACTIONS(231), 1,
      sym__space,
    ACTIONS(233), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_multiline_hint,
    ACTIONS(237), 1,
      sym__indent,
  [1486] = 3,
    ACTIONS(134), 1,
      sym_line_comment,
    STATE(102), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__endfile,
  [1497] = 4,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(223), 1,
      sym__indent,
    ACTIONS(239), 1,
      sym__outdent,
    STATE(100), 1,
      aux_sym__multiline_fragment_repeat1,
  [1510] = 3,
    ACTIONS(128), 1,
      sym_line_comment,
    STATE(75), 1,
      aux_sym__line_comments,
    ACTIONS(53), 2,
      sym__newline,
      sym__outdent,
  [1521] = 3,
    ACTIONS(192), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym__line_comments,
    ACTIONS(241), 2,
      sym__newline,
      sym__outdent,
  [1532] = 3,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(243), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1543] = 3,
    ACTIONS(192), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym__line_comments,
    ACTIONS(227), 2,
      sym__newline,
      sym__outdent,
  [1554] = 3,
    ACTIONS(248), 1,
      sym_line_comment,
    STATE(88), 1,
      aux_sym__line_comments,
    ACTIONS(227), 2,
      sym__newline,
      sym__outdent,
  [1565] = 3,
    ACTIONS(19), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__endfile,
  [1576] = 3,
    ACTIONS(192), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__outdent,
  [1587] = 3,
    ACTIONS(122), 1,
      sym_line_comment,
    STATE(93), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__outdent,
  [1598] = 3,
    ACTIONS(173), 1,
      sym_line_comment,
    STATE(90), 1,
      aux_sym__line_comments,
    ACTIONS(167), 2,
      sym__newline,
      sym__outdent,
  [1609] = 3,
    ACTIONS(250), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(217), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1620] = 3,
    ACTIONS(19), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym__line_comments,
    ACTIONS(241), 2,
      sym__newline,
      sym__endfile,
  [1631] = 3,
    ACTIONS(140), 1,
      sym_line_comment,
    STATE(92), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__endfile,
  [1642] = 3,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    STATE(105), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(252), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1653] = 4,
    ACTIONS(256), 1,
      sym__newline,
    ACTIONS(259), 1,
      sym__indent,
    ACTIONS(262), 1,
      sym__outdent,
    STATE(100), 1,
      aux_sym__multiline_fragment_repeat1,
  [1666] = 4,
    ACTIONS(264), 1,
      sym__space,
    ACTIONS(266), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_multiline_hint,
    ACTIONS(270), 1,
      sym__indent,
  [1679] = 3,
    ACTIONS(19), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym__line_comments,
    ACTIONS(120), 2,
      sym__newline,
      sym__endfile,
  [1690] = 3,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(217), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1701] = 3,
    ACTIONS(276), 1,
      anon_sym_DQUOTE,
    STATE(103), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(274), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1712] = 3,
    ACTIONS(278), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(217), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1723] = 3,
    ACTIONS(282), 1,
      anon_sym_DQUOTE,
    STATE(96), 1,
      aux_sym__quoted_literal_repeat1,
    ACTIONS(280), 2,
      sym_escape_sequence,
      aux_sym__quoted_literal_token1,
  [1734] = 3,
    ACTIONS(284), 1,
      sym__newline,
    ACTIONS(287), 1,
      sym__endfile,
    STATE(107), 1,
      aux_sym_list_repeat1,
  [1744] = 1,
    ACTIONS(289), 3,
      sym__newline,
      sym__indent,
      sym__outdent,
  [1750] = 1,
    ACTIONS(291), 3,
      sym__newline,
      sym__endfile,
      sym_line_comment,
  [1756] = 1,
    ACTIONS(293), 3,
      sym__newline,
      sym__endfile,
      sym_line_comment,
  [1762] = 1,
    ACTIONS(295), 3,
      sym__newline,
      sym__endfile,
      sym_line_comment,
  [1768] = 3,
    ACTIONS(297), 1,
      sym__newline,
    ACTIONS(300), 1,
      sym__endfile,
    STATE(112), 1,
      aux_sym_map_repeat1,
  [1778] = 3,
    ACTIONS(287), 1,
      sym__outdent,
    ACTIONS(302), 1,
      sym__newline,
    STATE(113), 1,
      aux_sym_list_repeat1,
  [1788] = 3,
    ACTIONS(300), 1,
      sym__outdent,
    ACTIONS(305), 1,
      sym__newline,
    STATE(114), 1,
      aux_sym_map_repeat1,
  [1798] = 3,
    ACTIONS(308), 1,
      sym__newline,
    ACTIONS(310), 1,
      sym__outdent,
    STATE(128), 1,
      aux_sym_list_repeat1,
  [1808] = 3,
    ACTIONS(312), 1,
      sym__newline,
    ACTIONS(314), 1,
      sym__outdent,
    STATE(130), 1,
      aux_sym_map_repeat1,
  [1818] = 3,
    ACTIONS(264), 1,
      sym__space,
    ACTIONS(266), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym__indent,
  [1828] = 1,
    ACTIONS(316), 3,
      sym__newline,
      sym__endfile,
      sym_line_comment,
  [1834] = 1,
    ACTIONS(262), 3,
      sym__newline,
      sym__indent,
      sym__outdent,
  [1840] = 1,
    ACTIONS(318), 3,
      sym__newline,
      sym__outdent,
      sym_line_comment,
  [1846] = 3,
    ACTIONS(320), 1,
      sym__newline,
    ACTIONS(322), 1,
      sym__endfile,
    STATE(112), 1,
      aux_sym_map_repeat1,
  [1856] = 3,
    ACTIONS(324), 1,
      sym__newline,
    ACTIONS(326), 1,
      sym__endfile,
    STATE(107), 1,
      aux_sym_list_repeat1,
  [1866] = 1,
    ACTIONS(318), 3,
      sym__newline,
      sym__endfile,
      sym_line_comment,
  [1872] = 1,
    ACTIONS(316), 3,
      sym__newline,
      sym__outdent,
      sym_line_comment,
  [1878] = 1,
    ACTIONS(291), 3,
      sym__newline,
      sym__outdent,
      sym_line_comment,
  [1884] = 1,
    ACTIONS(293), 3,
      sym__newline,
      sym__outdent,
      sym_line_comment,
  [1890] = 1,
    ACTIONS(295), 3,
      sym__newline,
      sym__outdent,
      sym_line_comment,
  [1896] = 3,
    ACTIONS(308), 1,
      sym__newline,
    ACTIONS(326), 1,
      sym__outdent,
    STATE(113), 1,
      aux_sym_list_repeat1,
  [1906] = 3,
    ACTIONS(314), 1,
      sym__endfile,
    ACTIONS(320), 1,
      sym__newline,
    STATE(121), 1,
      aux_sym_map_repeat1,
  [1916] = 3,
    ACTIONS(312), 1,
      sym__newline,
    ACTIONS(322), 1,
      sym__outdent,
    STATE(114), 1,
      aux_sym_map_repeat1,
  [1926] = 3,
    ACTIONS(310), 1,
      sym__endfile,
    ACTIONS(324), 1,
      sym__newline,
    STATE(122), 1,
      aux_sym_list_repeat1,
  [1936] = 3,
    ACTIONS(328), 1,
      sym__space,
    ACTIONS(330), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym__indent,
  [1946] = 3,
    ACTIONS(201), 1,
      sym__space,
    ACTIONS(203), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym__indent,
  [1956] = 3,
    ACTIONS(334), 1,
      sym__space,
    ACTIONS(336), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym__indent,
  [1966] = 1,
    ACTIONS(157), 2,
      sym__newline,
      sym__endfile,
  [1971] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(200), 1,
      sym__multiline_fragment,
  [1978] = 1,
    ACTIONS(93), 2,
      sym__newline,
      sym__outdent,
  [1983] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(178), 1,
      sym__multiline_fragment,
  [1990] = 2,
    ACTIONS(71), 1,
      anon_sym_EQ,
    STATE(147), 1,
      sym__item,
  [1997] = 1,
    ACTIONS(342), 2,
      sym__newline,
      sym__endfile,
  [2002] = 2,
    ACTIONS(344), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym__indent,
  [2009] = 2,
    ACTIONS(330), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym__indent,
  [2016] = 1,
    ACTIONS(348), 2,
      sym__newline,
      sym__endfile,
  [2021] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(192), 1,
      sym__multiline_fragment,
  [2028] = 1,
    ACTIONS(350), 2,
      sym__newline,
      sym__endfile,
  [2033] = 1,
    ACTIONS(157), 2,
      sym__newline,
      sym__outdent,
  [2038] = 1,
    ACTIONS(287), 2,
      sym__newline,
      sym__outdent,
  [2043] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(191), 1,
      sym__multiline_fragment,
  [2050] = 1,
    ACTIONS(300), 2,
      sym__newline,
      sym__outdent,
  [2055] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(218), 1,
      sym__multiline_fragment,
  [2062] = 1,
    ACTIONS(167), 2,
      sym__newline,
      sym__outdent,
  [2067] = 1,
    ACTIONS(93), 2,
      sym__newline,
      sym__endfile,
  [2072] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(189), 1,
      sym__multiline_fragment,
  [2079] = 2,
    ACTIONS(7), 1,
      anon_sym_EQ,
    STATE(171), 1,
      sym__item,
  [2086] = 1,
    ACTIONS(241), 2,
      sym__newline,
      sym__endfile,
  [2091] = 1,
    ACTIONS(183), 2,
      sym__newline,
      sym__outdent,
  [2096] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(186), 1,
      sym__multiline_fragment,
  [2103] = 1,
    ACTIONS(227), 2,
      sym__newline,
      sym__outdent,
  [2108] = 1,
    ACTIONS(352), 2,
      sym__newline,
      sym__endfile,
  [2113] = 2,
    ACTIONS(354), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym__indent,
  [2120] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(179), 1,
      sym__multiline_fragment,
  [2127] = 1,
    ACTIONS(352), 2,
      sym__newline,
      sym__outdent,
  [2132] = 1,
    ACTIONS(241), 2,
      sym__newline,
      sym__outdent,
  [2137] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(207), 1,
      sym__multiline_fragment,
  [2144] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(183), 1,
      sym__multiline_fragment,
  [2151] = 1,
    ACTIONS(350), 2,
      sym__newline,
      sym__outdent,
  [2156] = 1,
    ACTIONS(348), 2,
      sym__newline,
      sym__outdent,
  [2161] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(206), 1,
      sym__multiline_fragment,
  [2168] = 1,
    ACTIONS(342), 2,
      sym__newline,
      sym__outdent,
  [2173] = 2,
    ACTIONS(340), 1,
      aux_sym__multiline_fragment_token1,
    STATE(119), 1,
      sym__multiline_fragment,
  [2180] = 1,
    ACTIONS(287), 2,
      sym__newline,
      sym__endfile,
  [2185] = 1,
    ACTIONS(227), 2,
      sym__newline,
      sym__endfile,
  [2190] = 1,
    ACTIONS(300), 2,
      sym__newline,
      sym__endfile,
  [2195] = 1,
    ACTIONS(167), 2,
      sym__newline,
      sym__endfile,
  [2200] = 1,
    ACTIONS(183), 2,
      sym__newline,
      sym__endfile,
  [2205] = 2,
    ACTIONS(336), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym__indent,
  [2212] = 1,
    ACTIONS(338), 1,
      sym__indent,
  [2216] = 1,
    ACTIONS(358), 1,
      sym__outdent,
  [2220] = 1,
    ACTIONS(360), 1,
      sym__outdent,
  [2224] = 1,
    ACTIONS(362), 1,
      sym__outdent,
  [2228] = 1,
    ACTIONS(364), 1,
      sym__outdent,
  [2232] = 1,
    ACTIONS(366), 1,
      sym__outdent,
  [2236] = 1,
    ACTIONS(368), 1,
      sym__outdent,
  [2240] = 1,
    ACTIONS(370), 1,
      sym__outdent,
  [2244] = 1,
    ACTIONS(372), 1,
      sym__outdent,
  [2248] = 1,
    ACTIONS(374), 1,
      sym__outdent,
  [2252] = 1,
    ACTIONS(376), 1,
      sym__outdent,
  [2256] = 1,
    ACTIONS(378), 1,
      sym__outdent,
  [2260] = 1,
    ACTIONS(380), 1,
      sym__outdent,
  [2264] = 1,
    ACTIONS(382), 1,
      sym__outdent,
  [2268] = 1,
    ACTIONS(384), 1,
      sym__outdent,
  [2272] = 1,
    ACTIONS(386), 1,
      sym__outdent,
  [2276] = 1,
    ACTIONS(388), 1,
      sym__outdent,
  [2280] = 1,
    ACTIONS(390), 1,
      sym__outdent,
  [2284] = 1,
    ACTIONS(392), 1,
      ts_builtin_sym_end,
  [2288] = 1,
    ACTIONS(394), 1,
      sym__outdent,
  [2292] = 1,
    ACTIONS(396), 1,
      sym__endfile,
  [2296] = 1,
    ACTIONS(398), 1,
      sym__outdent,
  [2300] = 1,
    ACTIONS(270), 1,
      sym__indent,
  [2304] = 1,
    ACTIONS(400), 1,
      sym__outdent,
  [2308] = 1,
    ACTIONS(356), 1,
      sym__indent,
  [2312] = 1,
    ACTIONS(402), 1,
      sym__outdent,
  [2316] = 1,
    ACTIONS(404), 1,
      sym__outdent,
  [2320] = 1,
    ACTIONS(406), 1,
      ts_builtin_sym_end,
  [2324] = 1,
    ACTIONS(408), 1,
      sym__outdent,
  [2328] = 1,
    ACTIONS(410), 1,
      sym__outdent,
  [2332] = 1,
    ACTIONS(412), 1,
      sym__outdent,
  [2336] = 1,
    ACTIONS(414), 1,
      sym__indent,
  [2340] = 1,
    ACTIONS(416), 1,
      sym__outdent,
  [2344] = 1,
    ACTIONS(65), 1,
      sym__endfile,
  [2348] = 1,
    ACTIONS(418), 1,
      ts_builtin_sym_end,
  [2352] = 1,
    ACTIONS(207), 1,
      sym__indent,
  [2356] = 1,
    ACTIONS(17), 1,
      sym__endfile,
  [2360] = 1,
    ACTIONS(420), 1,
      ts_builtin_sym_end,
  [2364] = 1,
    ACTIONS(332), 1,
      sym__indent,
  [2368] = 1,
    ACTIONS(422), 1,
      ts_builtin_sym_end,
  [2372] = 1,
    ACTIONS(346), 1,
      sym__indent,
  [2376] = 1,
    ACTIONS(424), 1,
      sym__outdent,
  [2380] = 1,
    ACTIONS(426), 1,
      sym__indent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 77,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 185,
  [SMALL_STATE(8)] = 215,
  [SMALL_STATE(9)] = 245,
  [SMALL_STATE(10)] = 272,
  [SMALL_STATE(11)] = 299,
  [SMALL_STATE(12)] = 326,
  [SMALL_STATE(13)] = 353,
  [SMALL_STATE(14)] = 380,
  [SMALL_STATE(15)] = 407,
  [SMALL_STATE(16)] = 434,
  [SMALL_STATE(17)] = 461,
  [SMALL_STATE(18)] = 488,
  [SMALL_STATE(19)] = 515,
  [SMALL_STATE(20)] = 542,
  [SMALL_STATE(21)] = 569,
  [SMALL_STATE(22)] = 596,
  [SMALL_STATE(23)] = 623,
  [SMALL_STATE(24)] = 650,
  [SMALL_STATE(25)] = 677,
  [SMALL_STATE(26)] = 703,
  [SMALL_STATE(27)] = 729,
  [SMALL_STATE(28)] = 752,
  [SMALL_STATE(29)] = 775,
  [SMALL_STATE(30)] = 785,
  [SMALL_STATE(31)] = 795,
  [SMALL_STATE(32)] = 805,
  [SMALL_STATE(33)] = 819,
  [SMALL_STATE(34)] = 829,
  [SMALL_STATE(35)] = 839,
  [SMALL_STATE(36)] = 849,
  [SMALL_STATE(37)] = 866,
  [SMALL_STATE(38)] = 883,
  [SMALL_STATE(39)] = 900,
  [SMALL_STATE(40)] = 917,
  [SMALL_STATE(41)] = 929,
  [SMALL_STATE(42)] = 943,
  [SMALL_STATE(43)] = 957,
  [SMALL_STATE(44)] = 971,
  [SMALL_STATE(45)] = 985,
  [SMALL_STATE(46)] = 999,
  [SMALL_STATE(47)] = 1007,
  [SMALL_STATE(48)] = 1015,
  [SMALL_STATE(49)] = 1029,
  [SMALL_STATE(50)] = 1043,
  [SMALL_STATE(51)] = 1057,
  [SMALL_STATE(52)] = 1071,
  [SMALL_STATE(53)] = 1085,
  [SMALL_STATE(54)] = 1099,
  [SMALL_STATE(55)] = 1113,
  [SMALL_STATE(56)] = 1129,
  [SMALL_STATE(57)] = 1143,
  [SMALL_STATE(58)] = 1157,
  [SMALL_STATE(59)] = 1171,
  [SMALL_STATE(60)] = 1185,
  [SMALL_STATE(61)] = 1199,
  [SMALL_STATE(62)] = 1213,
  [SMALL_STATE(63)] = 1221,
  [SMALL_STATE(64)] = 1235,
  [SMALL_STATE(65)] = 1249,
  [SMALL_STATE(66)] = 1263,
  [SMALL_STATE(67)] = 1277,
  [SMALL_STATE(68)] = 1291,
  [SMALL_STATE(69)] = 1299,
  [SMALL_STATE(70)] = 1307,
  [SMALL_STATE(71)] = 1315,
  [SMALL_STATE(72)] = 1331,
  [SMALL_STATE(73)] = 1343,
  [SMALL_STATE(74)] = 1357,
  [SMALL_STATE(75)] = 1368,
  [SMALL_STATE(76)] = 1379,
  [SMALL_STATE(77)] = 1390,
  [SMALL_STATE(78)] = 1401,
  [SMALL_STATE(79)] = 1414,
  [SMALL_STATE(80)] = 1427,
  [SMALL_STATE(81)] = 1438,
  [SMALL_STATE(82)] = 1451,
  [SMALL_STATE(83)] = 1462,
  [SMALL_STATE(84)] = 1473,
  [SMALL_STATE(85)] = 1486,
  [SMALL_STATE(86)] = 1497,
  [SMALL_STATE(87)] = 1510,
  [SMALL_STATE(88)] = 1521,
  [SMALL_STATE(89)] = 1532,
  [SMALL_STATE(90)] = 1543,
  [SMALL_STATE(91)] = 1554,
  [SMALL_STATE(92)] = 1565,
  [SMALL_STATE(93)] = 1576,
  [SMALL_STATE(94)] = 1587,
  [SMALL_STATE(95)] = 1598,
  [SMALL_STATE(96)] = 1609,
  [SMALL_STATE(97)] = 1620,
  [SMALL_STATE(98)] = 1631,
  [SMALL_STATE(99)] = 1642,
  [SMALL_STATE(100)] = 1653,
  [SMALL_STATE(101)] = 1666,
  [SMALL_STATE(102)] = 1679,
  [SMALL_STATE(103)] = 1690,
  [SMALL_STATE(104)] = 1701,
  [SMALL_STATE(105)] = 1712,
  [SMALL_STATE(106)] = 1723,
  [SMALL_STATE(107)] = 1734,
  [SMALL_STATE(108)] = 1744,
  [SMALL_STATE(109)] = 1750,
  [SMALL_STATE(110)] = 1756,
  [SMALL_STATE(111)] = 1762,
  [SMALL_STATE(112)] = 1768,
  [SMALL_STATE(113)] = 1778,
  [SMALL_STATE(114)] = 1788,
  [SMALL_STATE(115)] = 1798,
  [SMALL_STATE(116)] = 1808,
  [SMALL_STATE(117)] = 1818,
  [SMALL_STATE(118)] = 1828,
  [SMALL_STATE(119)] = 1834,
  [SMALL_STATE(120)] = 1840,
  [SMALL_STATE(121)] = 1846,
  [SMALL_STATE(122)] = 1856,
  [SMALL_STATE(123)] = 1866,
  [SMALL_STATE(124)] = 1872,
  [SMALL_STATE(125)] = 1878,
  [SMALL_STATE(126)] = 1884,
  [SMALL_STATE(127)] = 1890,
  [SMALL_STATE(128)] = 1896,
  [SMALL_STATE(129)] = 1906,
  [SMALL_STATE(130)] = 1916,
  [SMALL_STATE(131)] = 1926,
  [SMALL_STATE(132)] = 1936,
  [SMALL_STATE(133)] = 1946,
  [SMALL_STATE(134)] = 1956,
  [SMALL_STATE(135)] = 1966,
  [SMALL_STATE(136)] = 1971,
  [SMALL_STATE(137)] = 1978,
  [SMALL_STATE(138)] = 1983,
  [SMALL_STATE(139)] = 1990,
  [SMALL_STATE(140)] = 1997,
  [SMALL_STATE(141)] = 2002,
  [SMALL_STATE(142)] = 2009,
  [SMALL_STATE(143)] = 2016,
  [SMALL_STATE(144)] = 2021,
  [SMALL_STATE(145)] = 2028,
  [SMALL_STATE(146)] = 2033,
  [SMALL_STATE(147)] = 2038,
  [SMALL_STATE(148)] = 2043,
  [SMALL_STATE(149)] = 2050,
  [SMALL_STATE(150)] = 2055,
  [SMALL_STATE(151)] = 2062,
  [SMALL_STATE(152)] = 2067,
  [SMALL_STATE(153)] = 2072,
  [SMALL_STATE(154)] = 2079,
  [SMALL_STATE(155)] = 2086,
  [SMALL_STATE(156)] = 2091,
  [SMALL_STATE(157)] = 2096,
  [SMALL_STATE(158)] = 2103,
  [SMALL_STATE(159)] = 2108,
  [SMALL_STATE(160)] = 2113,
  [SMALL_STATE(161)] = 2120,
  [SMALL_STATE(162)] = 2127,
  [SMALL_STATE(163)] = 2132,
  [SMALL_STATE(164)] = 2137,
  [SMALL_STATE(165)] = 2144,
  [SMALL_STATE(166)] = 2151,
  [SMALL_STATE(167)] = 2156,
  [SMALL_STATE(168)] = 2161,
  [SMALL_STATE(169)] = 2168,
  [SMALL_STATE(170)] = 2173,
  [SMALL_STATE(171)] = 2180,
  [SMALL_STATE(172)] = 2185,
  [SMALL_STATE(173)] = 2190,
  [SMALL_STATE(174)] = 2195,
  [SMALL_STATE(175)] = 2200,
  [SMALL_STATE(176)] = 2205,
  [SMALL_STATE(177)] = 2212,
  [SMALL_STATE(178)] = 2216,
  [SMALL_STATE(179)] = 2220,
  [SMALL_STATE(180)] = 2224,
  [SMALL_STATE(181)] = 2228,
  [SMALL_STATE(182)] = 2232,
  [SMALL_STATE(183)] = 2236,
  [SMALL_STATE(184)] = 2240,
  [SMALL_STATE(185)] = 2244,
  [SMALL_STATE(186)] = 2248,
  [SMALL_STATE(187)] = 2252,
  [SMALL_STATE(188)] = 2256,
  [SMALL_STATE(189)] = 2260,
  [SMALL_STATE(190)] = 2264,
  [SMALL_STATE(191)] = 2268,
  [SMALL_STATE(192)] = 2272,
  [SMALL_STATE(193)] = 2276,
  [SMALL_STATE(194)] = 2280,
  [SMALL_STATE(195)] = 2284,
  [SMALL_STATE(196)] = 2288,
  [SMALL_STATE(197)] = 2292,
  [SMALL_STATE(198)] = 2296,
  [SMALL_STATE(199)] = 2300,
  [SMALL_STATE(200)] = 2304,
  [SMALL_STATE(201)] = 2308,
  [SMALL_STATE(202)] = 2312,
  [SMALL_STATE(203)] = 2316,
  [SMALL_STATE(204)] = 2320,
  [SMALL_STATE(205)] = 2324,
  [SMALL_STATE(206)] = 2328,
  [SMALL_STATE(207)] = 2332,
  [SMALL_STATE(208)] = 2336,
  [SMALL_STATE(209)] = 2340,
  [SMALL_STATE(210)] = 2344,
  [SMALL_STATE(211)] = 2348,
  [SMALL_STATE(212)] = 2352,
  [SMALL_STATE(213)] = 2356,
  [SMALL_STATE(214)] = 2360,
  [SMALL_STATE(215)] = 2364,
  [SMALL_STATE(216)] = 2368,
  [SMALL_STATE(217)] = 2372,
  [SMALL_STATE(218)] = 2376,
  [SMALL_STATE(219)] = 2380,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(214),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(211),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(204),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_literal, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_literal, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line_comments, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_comments, 2, 0, 0), SHIFT_REPEAT(32),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_comments, 2, 0, 0), SHIFT_REPEAT(40),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_comments, 2, 0, 0), SHIFT_REPEAT(72),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_comments, 2, 0, 0), SHIFT_REPEAT(77),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(215),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(212),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_fragment, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(199),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_fragment, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 6, 0, 0),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quoted_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__quoted_literal_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(170),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(168),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(154),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 3, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 6, 0, 3),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 7, 0, 4),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 8, 0, 5),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [305] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 1, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 5, 0, 2),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 4, 0, 1),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(217),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(201),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 7, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(219),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 7, 0, 0),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 6, 0, 0),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 5, 0, 0),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(208),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(195),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [406] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [418] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [422] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__endfile = 1,
  ts_external_token__indent = 2,
  ts_external_token__outdent = 3,
  ts_external_token_line_comment = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__endfile] = sym__endfile,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__outdent] = sym__outdent,
  [ts_external_token_line_comment] = sym_line_comment,
};

static const bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__endfile] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__outdent] = true,
    [ts_external_token_line_comment] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__endfile] = true,
    [ts_external_token_line_comment] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__outdent] = true,
    [ts_external_token_line_comment] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__endfile] = true,
    [ts_external_token__indent] = true,
    [ts_external_token_line_comment] = true,
  },
  [5] = {
    [ts_external_token__endfile] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__outdent] = true,
    [ts_external_token_line_comment] = true,
  },
  [7] = {
    [ts_external_token__indent] = true,
  },
  [8] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__outdent] = true,
  },
  [9] = {
    [ts_external_token__newline] = true,
    [ts_external_token__endfile] = true,
  },
  [10] = {
    [ts_external_token__newline] = true,
    [ts_external_token__outdent] = true,
  },
  [11] = {
    [ts_external_token__outdent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_conl_external_scanner_create(void);
void tree_sitter_conl_external_scanner_destroy(void *);
bool tree_sitter_conl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_conl_external_scanner_serialize(void *, char *);
void tree_sitter_conl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_conl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_conl_external_scanner_create,
      tree_sitter_conl_external_scanner_destroy,
      tree_sitter_conl_external_scanner_scan,
      tree_sitter_conl_external_scanner_serialize,
      tree_sitter_conl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
