#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 174
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym__space = 1,
  sym_comment = 2,
  sym_escape_sequence = 3,
  sym_empty = 4,
  aux_sym_key_token1 = 5,
  aux_sym_key_token2 = 6,
  aux_sym_key_token3 = 7,
  aux_sym_value_token1 = 8,
  aux_sym_value_token2 = 9,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 10,
  sym_multiline_indicator = 11,
  aux_sym__multiline_fragment_token1 = 12,
  anon_sym_EQ = 13,
  sym__newline = 14,
  sym__endfile = 15,
  sym__indent = 16,
  sym__outdent = 17,
  sym_source_file = 18,
  sym__section = 19,
  sym_map = 20,
  sym_list = 21,
  sym_key = 22,
  sym_value = 23,
  sym_multiline_value = 24,
  sym__multiline_fragment = 25,
  sym__item = 26,
  sym_pair = 27,
  aux_sym_map_repeat1 = 28,
  aux_sym_list_repeat1 = 29,
  aux_sym_list_repeat2 = 30,
  aux_sym_key_repeat1 = 31,
  aux_sym_value_repeat1 = 32,
  aux_sym__multiline_fragment_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__space] = "_space",
  [sym_comment] = "comment",
  [sym_escape_sequence] = "escape_sequence",
  [sym_empty] = "empty",
  [aux_sym_key_token1] = "key_token1",
  [aux_sym_key_token2] = "key_token2",
  [aux_sym_key_token3] = "key_token3",
  [aux_sym_value_token1] = "value_token1",
  [aux_sym_value_token2] = "value_token2",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [sym_multiline_indicator] = "multiline_indicator",
  [aux_sym__multiline_fragment_token1] = "_multiline_fragment_token1",
  [anon_sym_EQ] = "=",
  [sym__newline] = "_newline",
  [sym__endfile] = "_endfile",
  [sym__indent] = "_indent",
  [sym__outdent] = "_outdent",
  [sym_source_file] = "source_file",
  [sym__section] = "_section",
  [sym_map] = "map",
  [sym_list] = "list",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym_multiline_value] = "multiline_value",
  [sym__multiline_fragment] = "_multiline_fragment",
  [sym__item] = "_item",
  [sym_pair] = "pair",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_list_repeat2] = "list_repeat2",
  [aux_sym_key_repeat1] = "key_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym__multiline_fragment_repeat1] = "_multiline_fragment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__space] = sym__space,
  [sym_comment] = sym_comment,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_empty] = sym_empty,
  [aux_sym_key_token1] = aux_sym_key_token1,
  [aux_sym_key_token2] = aux_sym_key_token2,
  [aux_sym_key_token3] = aux_sym_key_token3,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [aux_sym_value_token2] = aux_sym_value_token2,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [sym_multiline_indicator] = sym_multiline_indicator,
  [aux_sym__multiline_fragment_token1] = aux_sym__multiline_fragment_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym__newline] = sym__newline,
  [sym__endfile] = sym__endfile,
  [sym__indent] = sym__indent,
  [sym__outdent] = sym__outdent,
  [sym_source_file] = sym_source_file,
  [sym__section] = sym__section,
  [sym_map] = sym_map,
  [sym_list] = sym_list,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym_multiline_value] = sym_multiline_value,
  [sym__multiline_fragment] = sym__multiline_fragment,
  [sym__item] = sym__item,
  [sym_pair] = sym_pair,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_list_repeat2] = aux_sym_list_repeat2,
  [aux_sym_key_repeat1] = aux_sym_key_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym__multiline_fragment_repeat1] = aux_sym__multiline_fragment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_empty] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_key_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_multiline_indicator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__multiline_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__endfile] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__outdent] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__section] = {
    .visible = false,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_value] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_fragment] = {
    .visible = false,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 6,
  [12] = 9,
  [13] = 8,
  [14] = 10,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 21,
  [25] = 25,
  [26] = 20,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 32,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 37,
  [42] = 39,
  [43] = 40,
  [44] = 33,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 54,
  [58] = 58,
  [59] = 53,
  [60] = 60,
  [61] = 48,
  [62] = 62,
  [63] = 50,
  [64] = 49,
  [65] = 62,
  [66] = 51,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 46,
  [71] = 71,
  [72] = 47,
  [73] = 71,
  [74] = 68,
  [75] = 58,
  [76] = 60,
  [77] = 77,
  [78] = 78,
  [79] = 52,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 88,
  [90] = 82,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 87,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 91,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 96,
  [106] = 98,
  [107] = 107,
  [108] = 108,
  [109] = 104,
  [110] = 110,
  [111] = 100,
  [112] = 108,
  [113] = 86,
  [114] = 93,
  [115] = 115,
  [116] = 116,
  [117] = 115,
  [118] = 97,
  [119] = 119,
  [120] = 119,
  [121] = 116,
  [122] = 110,
  [123] = 107,
  [124] = 101,
  [125] = 83,
  [126] = 85,
  [127] = 81,
  [128] = 84,
  [129] = 92,
  [130] = 95,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 134,
  [141] = 141,
  [142] = 142,
  [143] = 137,
  [144] = 131,
  [145] = 132,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 139,
  [151] = 142,
  [152] = 141,
  [153] = 153,
  [154] = 154,
  [155] = 149,
  [156] = 153,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 147,
  [161] = 157,
  [162] = 162,
  [163] = 138,
  [164] = 164,
  [165] = 135,
  [166] = 166,
  [167] = 133,
  [168] = 168,
  [169] = 136,
  [170] = 170,
  [171] = 154,
  [172] = 146,
  [173] = 159,
};

static TSCharacterRange sym_multiline_indicator_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'$', '.'}, {'0', '<'}, {'?', '['}, {']', '^'},
  {'`', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '#' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '>' ||
          lookahead == '\\' ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if ((!eof && set_contains(sym_multiline_indicator_character_set_1, 9, lookahead))) ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '"' ||
          lookahead == '#' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '>' ||
          lookahead == '\\' ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '"' ||
          lookahead == '#' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '>' ||
          lookahead == '\\' ||
          lookahead == '_') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '}') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(29);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(31);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == '"') ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_empty);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_key_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_key_token2);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_key_token3);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_value_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_value_token2);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_multiline_indicator);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__multiline_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 3, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 1, .external_lex_state = 4},
  [16] = {.lex_state = 1, .external_lex_state = 4},
  [17] = {.lex_state = 1, .external_lex_state = 4},
  [18] = {.lex_state = 1, .external_lex_state = 4},
  [19] = {.lex_state = 4, .external_lex_state = 4},
  [20] = {.lex_state = 5, .external_lex_state = 2},
  [21] = {.lex_state = 5, .external_lex_state = 2},
  [22] = {.lex_state = 5, .external_lex_state = 5},
  [23] = {.lex_state = 5, .external_lex_state = 2},
  [24] = {.lex_state = 5, .external_lex_state = 5},
  [25] = {.lex_state = 4, .external_lex_state = 4},
  [26] = {.lex_state = 5, .external_lex_state = 5},
  [27] = {.lex_state = 4, .external_lex_state = 4},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3, .external_lex_state = 5},
  [31] = {.lex_state = 3, .external_lex_state = 2},
  [32] = {.lex_state = 3, .external_lex_state = 4},
  [33] = {.lex_state = 6, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 6},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 3, .external_lex_state = 4},
  [37] = {.lex_state = 3, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 6, .external_lex_state = 4},
  [41] = {.lex_state = 3, .external_lex_state = 4},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 6, .external_lex_state = 4},
  [44] = {.lex_state = 6, .external_lex_state = 4},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3, .external_lex_state = 2},
  [47] = {.lex_state = 3, .external_lex_state = 4},
  [48] = {.lex_state = 3, .external_lex_state = 2},
  [49] = {.lex_state = 3, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 3, .external_lex_state = 4},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3, .external_lex_state = 5},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 5},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 3, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 3, .external_lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 5},
  [64] = {.lex_state = 3, .external_lex_state = 5},
  [65] = {.lex_state = 0, .external_lex_state = 5},
  [66] = {.lex_state = 3, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 5},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 3, .external_lex_state = 5},
  [71] = {.lex_state = 3, .external_lex_state = 5},
  [72] = {.lex_state = 3, .external_lex_state = 4},
  [73] = {.lex_state = 3, .external_lex_state = 2},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 5},
  [76] = {.lex_state = 0, .external_lex_state = 5},
  [77] = {.lex_state = 3, .external_lex_state = 4},
  [78] = {.lex_state = 0, .external_lex_state = 6},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 0, .external_lex_state = 6},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 5},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 3, .external_lex_state = 4},
  [85] = {.lex_state = 0, .external_lex_state = 2},
  [86] = {.lex_state = 3, .external_lex_state = 4},
  [87] = {.lex_state = 17},
  [88] = {.lex_state = 17},
  [89] = {.lex_state = 17},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 17},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 17},
  [94] = {.lex_state = 17},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 17},
  [100] = {.lex_state = 17},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 17},
  [103] = {.lex_state = 17},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 5},
  [106] = {.lex_state = 0, .external_lex_state = 5},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 5},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 17},
  [112] = {.lex_state = 0, .external_lex_state = 5},
  [113] = {.lex_state = 3, .external_lex_state = 4},
  [114] = {.lex_state = 17},
  [115] = {.lex_state = 0, .external_lex_state = 5},
  [116] = {.lex_state = 0, .external_lex_state = 5},
  [117] = {.lex_state = 0, .external_lex_state = 2},
  [118] = {.lex_state = 0, .external_lex_state = 5},
  [119] = {.lex_state = 0, .external_lex_state = 5},
  [120] = {.lex_state = 0, .external_lex_state = 2},
  [121] = {.lex_state = 0, .external_lex_state = 2},
  [122] = {.lex_state = 0, .external_lex_state = 5},
  [123] = {.lex_state = 0, .external_lex_state = 5},
  [124] = {.lex_state = 0, .external_lex_state = 5},
  [125] = {.lex_state = 0, .external_lex_state = 5},
  [126] = {.lex_state = 0, .external_lex_state = 5},
  [127] = {.lex_state = 0, .external_lex_state = 5},
  [128] = {.lex_state = 3, .external_lex_state = 4},
  [129] = {.lex_state = 0, .external_lex_state = 5},
  [130] = {.lex_state = 0, .external_lex_state = 5},
  [131] = {.lex_state = 0, .external_lex_state = 7},
  [132] = {.lex_state = 0, .external_lex_state = 7},
  [133] = {.lex_state = 0, .external_lex_state = 4},
  [134] = {.lex_state = 0, .external_lex_state = 7},
  [135] = {.lex_state = 0, .external_lex_state = 4},
  [136] = {.lex_state = 0, .external_lex_state = 4},
  [137] = {.lex_state = 0, .external_lex_state = 7},
  [138] = {.lex_state = 0, .external_lex_state = 4},
  [139] = {.lex_state = 0, .external_lex_state = 7},
  [140] = {.lex_state = 0, .external_lex_state = 7},
  [141] = {.lex_state = 0, .external_lex_state = 7},
  [142] = {.lex_state = 0, .external_lex_state = 7},
  [143] = {.lex_state = 0, .external_lex_state = 7},
  [144] = {.lex_state = 0, .external_lex_state = 7},
  [145] = {.lex_state = 0, .external_lex_state = 7},
  [146] = {.lex_state = 0, .external_lex_state = 7},
  [147] = {.lex_state = 0, .external_lex_state = 7},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0, .external_lex_state = 7},
  [150] = {.lex_state = 0, .external_lex_state = 7},
  [151] = {.lex_state = 0, .external_lex_state = 7},
  [152] = {.lex_state = 0, .external_lex_state = 7},
  [153] = {.lex_state = 0, .external_lex_state = 7},
  [154] = {.lex_state = 0, .external_lex_state = 4},
  [155] = {.lex_state = 0, .external_lex_state = 7},
  [156] = {.lex_state = 0, .external_lex_state = 7},
  [157] = {.lex_state = 0, .external_lex_state = 4},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0, .external_lex_state = 4},
  [160] = {.lex_state = 0, .external_lex_state = 7},
  [161] = {.lex_state = 0, .external_lex_state = 4},
  [162] = {.lex_state = 0, .external_lex_state = 3},
  [163] = {.lex_state = 0, .external_lex_state = 4},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 0, .external_lex_state = 4},
  [166] = {.lex_state = 0, .external_lex_state = 3},
  [167] = {.lex_state = 0, .external_lex_state = 4},
  [168] = {.lex_state = 0, .external_lex_state = 7},
  [169] = {.lex_state = 0, .external_lex_state = 4},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0, .external_lex_state = 4},
  [172] = {.lex_state = 0, .external_lex_state = 7},
  [173] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_empty] = ACTIONS(1),
    [aux_sym_key_token1] = ACTIONS(1),
    [aux_sym_key_token2] = ACTIONS(1),
    [aux_sym_key_token3] = ACTIONS(1),
    [aux_sym_value_token1] = ACTIONS(1),
    [aux_sym_value_token2] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__endfile] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__outdent] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(170),
    [sym__section] = STATE(166),
    [sym_map] = STATE(166),
    [sym_list] = STATE(166),
    [sym_key] = STATE(37),
    [sym__item] = STATE(60),
    [sym_pair] = STATE(58),
    [aux_sym_list_repeat1] = STATE(39),
    [sym_comment] = ACTIONS(3),
    [sym_escape_sequence] = ACTIONS(5),
    [sym_empty] = ACTIONS(7),
    [aux_sym_key_token1] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(9),
    [sym__newline] = ACTIONS(11),
    [sym__endfile] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(15), 1,
      sym__endfile,
    STATE(37), 1,
      sym_key,
    STATE(39), 1,
      aux_sym_list_repeat1,
    STATE(58), 1,
      sym_pair,
    STATE(60), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(162), 3,
      sym__section,
      sym_map,
      sym_list,
  [34] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(150), 3,
      sym__section,
      sym_map,
      sym_list,
  [65] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(139), 3,
      sym__section,
      sym_map,
      sym_list,
  [96] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(140), 3,
      sym__section,
      sym_map,
      sym_list,
  [127] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(141), 3,
      sym__section,
      sym_map,
      sym_list,
  [158] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(134), 3,
      sym__section,
      sym_map,
      sym_list,
  [189] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(172), 3,
      sym__section,
      sym_map,
      sym_list,
  [220] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(143), 3,
      sym__section,
      sym_map,
      sym_list,
  [251] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(131), 3,
      sym__section,
      sym_map,
      sym_list,
  [282] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(152), 3,
      sym__section,
      sym_map,
      sym_list,
  [313] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(137), 3,
      sym__section,
      sym_map,
      sym_list,
  [344] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(146), 3,
      sym__section,
      sym_map,
      sym_list,
  [375] = 9,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_EQ,
    STATE(41), 1,
      sym_key,
    STATE(42), 1,
      aux_sym_list_repeat1,
    STATE(75), 1,
      sym_pair,
    STATE(76), 1,
      sym__item,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
    STATE(144), 3,
      sym__section,
      sym_map,
      sym_list,
  [406] = 9,
    ACTIONS(21), 1,
      sym__space,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym_escape_sequence,
    ACTIONS(27), 1,
      sym_empty,
    ACTIONS(29), 1,
      aux_sym_value_token1,
    ACTIONS(31), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym__indent,
    STATE(46), 1,
      sym_value,
    STATE(96), 1,
      sym_multiline_value,
  [434] = 9,
    ACTIONS(35), 1,
      sym__space,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_escape_sequence,
    ACTIONS(41), 1,
      sym_empty,
    ACTIONS(43), 1,
      aux_sym_value_token1,
    ACTIONS(45), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(47), 1,
      sym__indent,
    STATE(70), 1,
      sym_value,
    STATE(105), 1,
      sym_multiline_value,
  [462] = 8,
    ACTIONS(39), 1,
      sym_escape_sequence,
    ACTIONS(41), 1,
      sym_empty,
    ACTIONS(43), 1,
      aux_sym_value_token1,
    ACTIONS(45), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym__indent,
    STATE(64), 1,
      sym_value,
    STATE(112), 1,
      sym_multiline_value,
  [487] = 8,
    ACTIONS(25), 1,
      sym_escape_sequence,
    ACTIONS(27), 1,
      sym_empty,
    ACTIONS(29), 1,
      aux_sym_value_token1,
    ACTIONS(31), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(53), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym__indent,
    STATE(49), 1,
      sym_value,
    STATE(108), 1,
      sym_multiline_value,
  [512] = 5,
    ACTIONS(57), 1,
      sym__space,
    ACTIONS(61), 1,
      aux_sym_key_token2,
    STATE(25), 1,
      aux_sym_key_repeat1,
    ACTIONS(59), 2,
      sym_escape_sequence,
      aux_sym_key_token3,
    ACTIONS(63), 2,
      sym__indent,
      anon_sym_EQ,
  [530] = 4,
    ACTIONS(65), 1,
      sym__space,
    STATE(21), 1,
      aux_sym_value_repeat1,
    ACTIONS(69), 2,
      sym__newline,
      sym__endfile,
    ACTIONS(67), 3,
      sym_escape_sequence,
      aux_sym_key_token2,
      aux_sym_value_token2,
  [546] = 4,
    ACTIONS(71), 1,
      sym__space,
    STATE(23), 1,
      aux_sym_value_repeat1,
    ACTIONS(75), 2,
      sym__newline,
      sym__endfile,
    ACTIONS(73), 3,
      sym_escape_sequence,
      aux_sym_key_token2,
      aux_sym_value_token2,
  [562] = 4,
    ACTIONS(77), 1,
      sym__space,
    STATE(22), 1,
      aux_sym_value_repeat1,
    ACTIONS(82), 2,
      sym__newline,
      sym__outdent,
    ACTIONS(79), 3,
      sym_escape_sequence,
      aux_sym_key_token2,
      aux_sym_value_token2,
  [578] = 4,
    ACTIONS(77), 1,
      sym__space,
    STATE(23), 1,
      aux_sym_value_repeat1,
    ACTIONS(82), 2,
      sym__newline,
      sym__endfile,
    ACTIONS(84), 3,
      sym_escape_sequence,
      aux_sym_key_token2,
      aux_sym_value_token2,
  [594] = 4,
    ACTIONS(71), 1,
      sym__space,
    STATE(22), 1,
      aux_sym_value_repeat1,
    ACTIONS(75), 2,
      sym__newline,
      sym__outdent,
    ACTIONS(87), 3,
      sym_escape_sequence,
      aux_sym_key_token2,
      aux_sym_value_token2,
  [610] = 5,
    ACTIONS(89), 1,
      sym__space,
    ACTIONS(94), 1,
      aux_sym_key_token2,
    STATE(25), 1,
      aux_sym_key_repeat1,
    ACTIONS(91), 2,
      sym_escape_sequence,
      aux_sym_key_token3,
    ACTIONS(97), 2,
      sym__indent,
      anon_sym_EQ,
  [628] = 4,
    ACTIONS(65), 1,
      sym__space,
    STATE(24), 1,
      aux_sym_value_repeat1,
    ACTIONS(69), 2,
      sym__newline,
      sym__outdent,
    ACTIONS(99), 3,
      sym_escape_sequence,
      aux_sym_key_token2,
      aux_sym_value_token2,
  [644] = 5,
    ACTIONS(101), 1,
      sym__space,
    ACTIONS(105), 1,
      aux_sym_key_token2,
    STATE(19), 1,
      aux_sym_key_repeat1,
    ACTIONS(103), 2,
      sym_escape_sequence,
      aux_sym_key_token3,
    ACTIONS(107), 2,
      sym__indent,
      anon_sym_EQ,
  [662] = 5,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(109), 1,
      sym_comment,
    STATE(41), 1,
      sym_key,
    STATE(109), 1,
      sym_pair,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
  [679] = 5,
    ACTIONS(7), 1,
      sym_empty,
    ACTIONS(111), 1,
      sym_comment,
    STATE(37), 1,
      sym_key,
    STATE(104), 1,
      sym_pair,
    ACTIONS(5), 2,
      sym_escape_sequence,
      aux_sym_key_token1,
  [696] = 4,
    ACTIONS(115), 1,
      sym__newline,
    ACTIONS(117), 1,
      sym__outdent,
    STATE(63), 1,
      aux_sym_map_repeat1,
    ACTIONS(113), 2,
      sym_comment,
      anon_sym_EQ,
  [710] = 4,
    ACTIONS(117), 1,
      sym__endfile,
    ACTIONS(119), 1,
      sym__newline,
    STATE(50), 1,
      aux_sym_map_repeat1,
    ACTIONS(113), 2,
      sym_comment,
      anon_sym_EQ,
  [724] = 4,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(121), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym__indent,
    STATE(115), 1,
      sym__item,
  [737] = 4,
    ACTIONS(125), 1,
      sym__space,
    ACTIONS(127), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_multiline_indicator,
    ACTIONS(131), 1,
      sym__indent,
  [750] = 4,
    ACTIONS(133), 1,
      sym__newline,
    ACTIONS(136), 1,
      sym__indent,
    ACTIONS(139), 1,
      sym__outdent,
    STATE(34), 1,
      aux_sym__multiline_fragment_repeat1,
  [763] = 4,
    ACTIONS(141), 1,
      sym__newline,
    ACTIONS(143), 1,
      sym__indent,
    ACTIONS(145), 1,
      sym__outdent,
    STATE(34), 1,
      aux_sym__multiline_fragment_repeat1,
  [776] = 4,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(147), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym__indent,
    STATE(117), 1,
      sym__item,
  [789] = 4,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(151), 1,
      sym__space,
    ACTIONS(153), 1,
      sym__indent,
    STATE(98), 1,
      sym__item,
  [802] = 4,
    ACTIONS(141), 1,
      sym__newline,
    ACTIONS(143), 1,
      sym__indent,
    ACTIONS(155), 1,
      sym__outdent,
    STATE(35), 1,
      aux_sym__multiline_fragment_repeat1,
  [815] = 4,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(157), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_list_repeat1,
    STATE(69), 1,
      sym__item,
  [828] = 4,
    ACTIONS(159), 1,
      sym__space,
    ACTIONS(161), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_multiline_indicator,
    ACTIONS(165), 1,
      sym__indent,
  [841] = 4,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(167), 1,
      sym__space,
    ACTIONS(169), 1,
      sym__indent,
    STATE(106), 1,
      sym__item,
  [854] = 4,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(157), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_list_repeat1,
    STATE(67), 1,
      sym__item,
  [867] = 4,
    ACTIONS(171), 1,
      sym__space,
    ACTIONS(173), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_multiline_indicator,
    ACTIONS(177), 1,
      sym__indent,
  [880] = 4,
    ACTIONS(179), 1,
      sym__space,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_multiline_indicator,
    ACTIONS(185), 1,
      sym__indent,
  [893] = 3,
    ACTIONS(187), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_EQ,
    STATE(45), 1,
      aux_sym_list_repeat1,
  [903] = 2,
    ACTIONS(192), 1,
      sym__space,
    ACTIONS(194), 2,
      sym__newline,
      sym__endfile,
  [911] = 3,
    ACTIONS(179), 1,
      sym__space,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__indent,
  [921] = 2,
    ACTIONS(196), 1,
      sym_comment,
    ACTIONS(198), 2,
      sym__newline,
      sym__endfile,
  [929] = 2,
    ACTIONS(200), 1,
      sym__space,
    ACTIONS(198), 2,
      sym__newline,
      sym__endfile,
  [937] = 3,
    ACTIONS(119), 1,
      sym__newline,
    ACTIONS(202), 1,
      sym__endfile,
    STATE(62), 1,
      aux_sym_map_repeat1,
  [947] = 3,
    ACTIONS(204), 1,
      sym__space,
    ACTIONS(206), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym__indent,
  [957] = 3,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(210), 1,
      sym_comment,
    STATE(116), 1,
      sym__item,
  [967] = 2,
    ACTIONS(212), 1,
      sym_comment,
    ACTIONS(214), 2,
      sym__newline,
      sym__outdent,
  [975] = 3,
    ACTIONS(216), 1,
      sym__newline,
    ACTIONS(219), 1,
      sym__endfile,
    STATE(54), 1,
      aux_sym_list_repeat2,
  [985] = 3,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(223), 1,
      sym__endfile,
    STATE(54), 1,
      aux_sym_list_repeat2,
  [995] = 3,
    ACTIONS(223), 1,
      sym__outdent,
    ACTIONS(225), 1,
      sym__newline,
    STATE(57), 1,
      aux_sym_list_repeat2,
  [1005] = 3,
    ACTIONS(219), 1,
      sym__outdent,
    ACTIONS(227), 1,
      sym__newline,
    STATE(57), 1,
      aux_sym_list_repeat2,
  [1015] = 3,
    ACTIONS(117), 1,
      sym__endfile,
    ACTIONS(119), 1,
      sym__newline,
    STATE(50), 1,
      aux_sym_map_repeat1,
  [1025] = 2,
    ACTIONS(230), 1,
      sym_comment,
    ACTIONS(214), 2,
      sym__newline,
      sym__endfile,
  [1033] = 3,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(232), 1,
      sym__endfile,
    STATE(74), 1,
      aux_sym_list_repeat2,
  [1043] = 2,
    ACTIONS(234), 1,
      sym_comment,
    ACTIONS(198), 2,
      sym__newline,
      sym__outdent,
  [1051] = 3,
    ACTIONS(236), 1,
      sym__newline,
    ACTIONS(239), 1,
      sym__endfile,
    STATE(62), 1,
      aux_sym_map_repeat1,
  [1061] = 3,
    ACTIONS(115), 1,
      sym__newline,
    ACTIONS(202), 1,
      sym__outdent,
    STATE(65), 1,
      aux_sym_map_repeat1,
  [1071] = 2,
    ACTIONS(241), 1,
      sym__space,
    ACTIONS(198), 2,
      sym__newline,
      sym__outdent,
  [1079] = 3,
    ACTIONS(239), 1,
      sym__outdent,
    ACTIONS(243), 1,
      sym__newline,
    STATE(65), 1,
      aux_sym_map_repeat1,
  [1089] = 3,
    ACTIONS(246), 1,
      sym__space,
    ACTIONS(248), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym__indent,
  [1099] = 3,
    ACTIONS(225), 1,
      sym__newline,
    ACTIONS(252), 1,
      sym__outdent,
    STATE(56), 1,
      aux_sym_list_repeat2,
  [1109] = 3,
    ACTIONS(225), 1,
      sym__newline,
    ACTIONS(252), 1,
      sym__outdent,
    STATE(57), 1,
      aux_sym_list_repeat2,
  [1119] = 3,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(252), 1,
      sym__endfile,
    STATE(55), 1,
      aux_sym_list_repeat2,
  [1129] = 2,
    ACTIONS(254), 1,
      sym__space,
    ACTIONS(194), 2,
      sym__newline,
      sym__outdent,
  [1137] = 1,
    ACTIONS(69), 3,
      sym__newline,
      sym__outdent,
      sym__space,
  [1143] = 3,
    ACTIONS(125), 1,
      sym__space,
    ACTIONS(127), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym__indent,
  [1153] = 1,
    ACTIONS(69), 3,
      sym__newline,
      sym__endfile,
      sym__space,
  [1159] = 3,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(252), 1,
      sym__endfile,
    STATE(54), 1,
      aux_sym_list_repeat2,
  [1169] = 3,
    ACTIONS(115), 1,
      sym__newline,
    ACTIONS(117), 1,
      sym__outdent,
    STATE(63), 1,
      aux_sym_map_repeat1,
  [1179] = 3,
    ACTIONS(225), 1,
      sym__newline,
    ACTIONS(232), 1,
      sym__outdent,
    STATE(68), 1,
      aux_sym_list_repeat2,
  [1189] = 1,
    ACTIONS(107), 3,
      sym__indent,
      sym__space,
      anon_sym_EQ,
  [1195] = 1,
    ACTIONS(256), 3,
      sym__newline,
      sym__indent,
      sym__outdent,
  [1201] = 3,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(258), 1,
      sym_comment,
    STATE(121), 1,
      sym__item,
  [1211] = 1,
    ACTIONS(139), 3,
      sym__newline,
      sym__indent,
      sym__outdent,
  [1217] = 1,
    ACTIONS(260), 2,
      sym__newline,
      sym__endfile,
  [1222] = 1,
    ACTIONS(262), 2,
      sym__newline,
      sym__outdent,
  [1227] = 1,
    ACTIONS(264), 2,
      sym__newline,
      sym__endfile,
  [1232] = 2,
    ACTIONS(266), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym__indent,
  [1239] = 1,
    ACTIONS(270), 2,
      sym__newline,
      sym__endfile,
  [1244] = 2,
    ACTIONS(206), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym__indent,
  [1251] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(149), 1,
      sym__multiline_fragment,
  [1258] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(156), 1,
      sym__multiline_fragment,
  [1265] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(153), 1,
      sym__multiline_fragment,
  [1272] = 1,
    ACTIONS(262), 2,
      sym__newline,
      sym__endfile,
  [1277] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(147), 1,
      sym__multiline_fragment,
  [1284] = 1,
    ACTIONS(274), 2,
      sym__newline,
      sym__endfile,
  [1289] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(145), 1,
      sym__multiline_fragment,
  [1296] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(155), 1,
      sym__multiline_fragment,
  [1303] = 1,
    ACTIONS(276), 2,
      sym__newline,
      sym__endfile,
  [1308] = 1,
    ACTIONS(194), 2,
      sym__newline,
      sym__endfile,
  [1313] = 1,
    ACTIONS(278), 2,
      sym__newline,
      sym__endfile,
  [1318] = 1,
    ACTIONS(280), 2,
      sym__newline,
      sym__endfile,
  [1323] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(160), 1,
      sym__multiline_fragment,
  [1330] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(142), 1,
      sym__multiline_fragment,
  [1337] = 1,
    ACTIONS(282), 2,
      sym__newline,
      sym__endfile,
  [1342] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(168), 1,
      sym__multiline_fragment,
  [1349] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(80), 1,
      sym__multiline_fragment,
  [1356] = 1,
    ACTIONS(239), 2,
      sym__newline,
      sym__endfile,
  [1361] = 1,
    ACTIONS(194), 2,
      sym__newline,
      sym__outdent,
  [1366] = 1,
    ACTIONS(280), 2,
      sym__newline,
      sym__outdent,
  [1371] = 1,
    ACTIONS(284), 2,
      sym__newline,
      sym__endfile,
  [1376] = 1,
    ACTIONS(198), 2,
      sym__newline,
      sym__endfile,
  [1381] = 1,
    ACTIONS(239), 2,
      sym__newline,
      sym__outdent,
  [1386] = 1,
    ACTIONS(286), 2,
      sym__newline,
      sym__endfile,
  [1391] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(151), 1,
      sym__multiline_fragment,
  [1398] = 1,
    ACTIONS(198), 2,
      sym__newline,
      sym__outdent,
  [1403] = 2,
    ACTIONS(248), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym__indent,
  [1410] = 2,
    ACTIONS(272), 1,
      aux_sym__multiline_fragment_token1,
    STATE(132), 1,
      sym__multiline_fragment,
  [1417] = 1,
    ACTIONS(288), 2,
      sym__newline,
      sym__outdent,
  [1422] = 1,
    ACTIONS(219), 2,
      sym__newline,
      sym__outdent,
  [1427] = 1,
    ACTIONS(288), 2,
      sym__newline,
      sym__endfile,
  [1432] = 1,
    ACTIONS(278), 2,
      sym__newline,
      sym__outdent,
  [1437] = 1,
    ACTIONS(214), 2,
      sym__newline,
      sym__outdent,
  [1442] = 1,
    ACTIONS(214), 2,
      sym__newline,
      sym__endfile,
  [1447] = 1,
    ACTIONS(219), 2,
      sym__newline,
      sym__endfile,
  [1452] = 1,
    ACTIONS(286), 2,
      sym__newline,
      sym__outdent,
  [1457] = 1,
    ACTIONS(284), 2,
      sym__newline,
      sym__outdent,
  [1462] = 1,
    ACTIONS(282), 2,
      sym__newline,
      sym__outdent,
  [1467] = 1,
    ACTIONS(264), 2,
      sym__newline,
      sym__outdent,
  [1472] = 1,
    ACTIONS(270), 2,
      sym__newline,
      sym__outdent,
  [1477] = 1,
    ACTIONS(260), 2,
      sym__newline,
      sym__outdent,
  [1482] = 2,
    ACTIONS(290), 1,
      sym_comment,
    ACTIONS(292), 1,
      sym__indent,
  [1489] = 1,
    ACTIONS(274), 2,
      sym__newline,
      sym__outdent,
  [1494] = 1,
    ACTIONS(276), 2,
      sym__newline,
      sym__outdent,
  [1499] = 1,
    ACTIONS(294), 1,
      sym__outdent,
  [1503] = 1,
    ACTIONS(296), 1,
      sym__outdent,
  [1507] = 1,
    ACTIONS(298), 1,
      sym__indent,
  [1511] = 1,
    ACTIONS(300), 1,
      sym__outdent,
  [1515] = 1,
    ACTIONS(185), 1,
      sym__indent,
  [1519] = 1,
    ACTIONS(250), 1,
      sym__indent,
  [1523] = 1,
    ACTIONS(302), 1,
      sym__outdent,
  [1527] = 1,
    ACTIONS(304), 1,
      sym__indent,
  [1531] = 1,
    ACTIONS(234), 1,
      sym__outdent,
  [1535] = 1,
    ACTIONS(306), 1,
      sym__outdent,
  [1539] = 1,
    ACTIONS(212), 1,
      sym__outdent,
  [1543] = 1,
    ACTIONS(308), 1,
      sym__outdent,
  [1547] = 1,
    ACTIONS(310), 1,
      sym__outdent,
  [1551] = 1,
    ACTIONS(312), 1,
      sym__outdent,
  [1555] = 1,
    ACTIONS(314), 1,
      sym__outdent,
  [1559] = 1,
    ACTIONS(316), 1,
      sym__outdent,
  [1563] = 1,
    ACTIONS(318), 1,
      sym__outdent,
  [1567] = 1,
    ACTIONS(320), 1,
      ts_builtin_sym_end,
  [1571] = 1,
    ACTIONS(322), 1,
      sym__outdent,
  [1575] = 1,
    ACTIONS(196), 1,
      sym__outdent,
  [1579] = 1,
    ACTIONS(324), 1,
      sym__outdent,
  [1583] = 1,
    ACTIONS(230), 1,
      sym__outdent,
  [1587] = 1,
    ACTIONS(326), 1,
      sym__outdent,
  [1591] = 1,
    ACTIONS(292), 1,
      sym__indent,
  [1595] = 1,
    ACTIONS(328), 1,
      sym__outdent,
  [1599] = 1,
    ACTIONS(330), 1,
      sym__outdent,
  [1603] = 1,
    ACTIONS(55), 1,
      sym__indent,
  [1607] = 1,
    ACTIONS(332), 1,
      ts_builtin_sym_end,
  [1611] = 1,
    ACTIONS(334), 1,
      sym__indent,
  [1615] = 1,
    ACTIONS(336), 1,
      sym__outdent,
  [1619] = 1,
    ACTIONS(51), 1,
      sym__indent,
  [1623] = 1,
    ACTIONS(338), 1,
      sym__endfile,
  [1627] = 1,
    ACTIONS(340), 1,
      sym__indent,
  [1631] = 1,
    ACTIONS(342), 1,
      ts_builtin_sym_end,
  [1635] = 1,
    ACTIONS(131), 1,
      sym__indent,
  [1639] = 1,
    ACTIONS(15), 1,
      sym__endfile,
  [1643] = 1,
    ACTIONS(344), 1,
      sym__indent,
  [1647] = 1,
    ACTIONS(346), 1,
      sym__outdent,
  [1651] = 1,
    ACTIONS(208), 1,
      sym__indent,
  [1655] = 1,
    ACTIONS(348), 1,
      ts_builtin_sym_end,
  [1659] = 1,
    ACTIONS(268), 1,
      sym__indent,
  [1663] = 1,
    ACTIONS(350), 1,
      sym__outdent,
  [1667] = 1,
    ACTIONS(352), 1,
      sym__indent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 65,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 127,
  [SMALL_STATE(7)] = 158,
  [SMALL_STATE(8)] = 189,
  [SMALL_STATE(9)] = 220,
  [SMALL_STATE(10)] = 251,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 313,
  [SMALL_STATE(13)] = 344,
  [SMALL_STATE(14)] = 375,
  [SMALL_STATE(15)] = 406,
  [SMALL_STATE(16)] = 434,
  [SMALL_STATE(17)] = 462,
  [SMALL_STATE(18)] = 487,
  [SMALL_STATE(19)] = 512,
  [SMALL_STATE(20)] = 530,
  [SMALL_STATE(21)] = 546,
  [SMALL_STATE(22)] = 562,
  [SMALL_STATE(23)] = 578,
  [SMALL_STATE(24)] = 594,
  [SMALL_STATE(25)] = 610,
  [SMALL_STATE(26)] = 628,
  [SMALL_STATE(27)] = 644,
  [SMALL_STATE(28)] = 662,
  [SMALL_STATE(29)] = 679,
  [SMALL_STATE(30)] = 696,
  [SMALL_STATE(31)] = 710,
  [SMALL_STATE(32)] = 724,
  [SMALL_STATE(33)] = 737,
  [SMALL_STATE(34)] = 750,
  [SMALL_STATE(35)] = 763,
  [SMALL_STATE(36)] = 776,
  [SMALL_STATE(37)] = 789,
  [SMALL_STATE(38)] = 802,
  [SMALL_STATE(39)] = 815,
  [SMALL_STATE(40)] = 828,
  [SMALL_STATE(41)] = 841,
  [SMALL_STATE(42)] = 854,
  [SMALL_STATE(43)] = 867,
  [SMALL_STATE(44)] = 880,
  [SMALL_STATE(45)] = 893,
  [SMALL_STATE(46)] = 903,
  [SMALL_STATE(47)] = 911,
  [SMALL_STATE(48)] = 921,
  [SMALL_STATE(49)] = 929,
  [SMALL_STATE(50)] = 937,
  [SMALL_STATE(51)] = 947,
  [SMALL_STATE(52)] = 957,
  [SMALL_STATE(53)] = 967,
  [SMALL_STATE(54)] = 975,
  [SMALL_STATE(55)] = 985,
  [SMALL_STATE(56)] = 995,
  [SMALL_STATE(57)] = 1005,
  [SMALL_STATE(58)] = 1015,
  [SMALL_STATE(59)] = 1025,
  [SMALL_STATE(60)] = 1033,
  [SMALL_STATE(61)] = 1043,
  [SMALL_STATE(62)] = 1051,
  [SMALL_STATE(63)] = 1061,
  [SMALL_STATE(64)] = 1071,
  [SMALL_STATE(65)] = 1079,
  [SMALL_STATE(66)] = 1089,
  [SMALL_STATE(67)] = 1099,
  [SMALL_STATE(68)] = 1109,
  [SMALL_STATE(69)] = 1119,
  [SMALL_STATE(70)] = 1129,
  [SMALL_STATE(71)] = 1137,
  [SMALL_STATE(72)] = 1143,
  [SMALL_STATE(73)] = 1153,
  [SMALL_STATE(74)] = 1159,
  [SMALL_STATE(75)] = 1169,
  [SMALL_STATE(76)] = 1179,
  [SMALL_STATE(77)] = 1189,
  [SMALL_STATE(78)] = 1195,
  [SMALL_STATE(79)] = 1201,
  [SMALL_STATE(80)] = 1211,
  [SMALL_STATE(81)] = 1217,
  [SMALL_STATE(82)] = 1222,
  [SMALL_STATE(83)] = 1227,
  [SMALL_STATE(84)] = 1232,
  [SMALL_STATE(85)] = 1239,
  [SMALL_STATE(86)] = 1244,
  [SMALL_STATE(87)] = 1251,
  [SMALL_STATE(88)] = 1258,
  [SMALL_STATE(89)] = 1265,
  [SMALL_STATE(90)] = 1272,
  [SMALL_STATE(91)] = 1277,
  [SMALL_STATE(92)] = 1284,
  [SMALL_STATE(93)] = 1289,
  [SMALL_STATE(94)] = 1296,
  [SMALL_STATE(95)] = 1303,
  [SMALL_STATE(96)] = 1308,
  [SMALL_STATE(97)] = 1313,
  [SMALL_STATE(98)] = 1318,
  [SMALL_STATE(99)] = 1323,
  [SMALL_STATE(100)] = 1330,
  [SMALL_STATE(101)] = 1337,
  [SMALL_STATE(102)] = 1342,
  [SMALL_STATE(103)] = 1349,
  [SMALL_STATE(104)] = 1356,
  [SMALL_STATE(105)] = 1361,
  [SMALL_STATE(106)] = 1366,
  [SMALL_STATE(107)] = 1371,
  [SMALL_STATE(108)] = 1376,
  [SMALL_STATE(109)] = 1381,
  [SMALL_STATE(110)] = 1386,
  [SMALL_STATE(111)] = 1391,
  [SMALL_STATE(112)] = 1398,
  [SMALL_STATE(113)] = 1403,
  [SMALL_STATE(114)] = 1410,
  [SMALL_STATE(115)] = 1417,
  [SMALL_STATE(116)] = 1422,
  [SMALL_STATE(117)] = 1427,
  [SMALL_STATE(118)] = 1432,
  [SMALL_STATE(119)] = 1437,
  [SMALL_STATE(120)] = 1442,
  [SMALL_STATE(121)] = 1447,
  [SMALL_STATE(122)] = 1452,
  [SMALL_STATE(123)] = 1457,
  [SMALL_STATE(124)] = 1462,
  [SMALL_STATE(125)] = 1467,
  [SMALL_STATE(126)] = 1472,
  [SMALL_STATE(127)] = 1477,
  [SMALL_STATE(128)] = 1482,
  [SMALL_STATE(129)] = 1489,
  [SMALL_STATE(130)] = 1494,
  [SMALL_STATE(131)] = 1499,
  [SMALL_STATE(132)] = 1503,
  [SMALL_STATE(133)] = 1507,
  [SMALL_STATE(134)] = 1511,
  [SMALL_STATE(135)] = 1515,
  [SMALL_STATE(136)] = 1519,
  [SMALL_STATE(137)] = 1523,
  [SMALL_STATE(138)] = 1527,
  [SMALL_STATE(139)] = 1531,
  [SMALL_STATE(140)] = 1535,
  [SMALL_STATE(141)] = 1539,
  [SMALL_STATE(142)] = 1543,
  [SMALL_STATE(143)] = 1547,
  [SMALL_STATE(144)] = 1551,
  [SMALL_STATE(145)] = 1555,
  [SMALL_STATE(146)] = 1559,
  [SMALL_STATE(147)] = 1563,
  [SMALL_STATE(148)] = 1567,
  [SMALL_STATE(149)] = 1571,
  [SMALL_STATE(150)] = 1575,
  [SMALL_STATE(151)] = 1579,
  [SMALL_STATE(152)] = 1583,
  [SMALL_STATE(153)] = 1587,
  [SMALL_STATE(154)] = 1591,
  [SMALL_STATE(155)] = 1595,
  [SMALL_STATE(156)] = 1599,
  [SMALL_STATE(157)] = 1603,
  [SMALL_STATE(158)] = 1607,
  [SMALL_STATE(159)] = 1611,
  [SMALL_STATE(160)] = 1615,
  [SMALL_STATE(161)] = 1619,
  [SMALL_STATE(162)] = 1623,
  [SMALL_STATE(163)] = 1627,
  [SMALL_STATE(164)] = 1631,
  [SMALL_STATE(165)] = 1635,
  [SMALL_STATE(166)] = 1639,
  [SMALL_STATE(167)] = 1643,
  [SMALL_STATE(168)] = 1647,
  [SMALL_STATE(169)] = 1651,
  [SMALL_STATE(170)] = 1655,
  [SMALL_STATE(171)] = 1659,
  [SMALL_STATE(172)] = 1663,
  [SMALL_STATE(173)] = 1667,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_fragment, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_fragment, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 4, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat2, 2, 0, 0), SHIFT_REPEAT(79),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat2, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat2, 2, 0, 0), SHIFT_REPEAT(52),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_fragment_repeat1, 3, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 5, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 6, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 5, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 6, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 6, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 7, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 8, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 4, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 5, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 4, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [348] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__endfile = 1,
  ts_external_token__indent = 2,
  ts_external_token__outdent = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__endfile] = sym__endfile,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__outdent] = sym__outdent,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__endfile] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__outdent] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__endfile] = true,
  },
  [3] = {
    [ts_external_token__endfile] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__outdent] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__outdent] = true,
  },
  [7] = {
    [ts_external_token__outdent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_conl_external_scanner_create(void);
void tree_sitter_conl_external_scanner_destroy(void *);
bool tree_sitter_conl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_conl_external_scanner_serialize(void *, char *);
void tree_sitter_conl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_conl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_conl_external_scanner_create,
      tree_sitter_conl_external_scanner_destroy,
      tree_sitter_conl_external_scanner_scan,
      tree_sitter_conl_external_scanner_serialize,
      tree_sitter_conl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
